### ISSUE TITLE
Loading component rendered on server

### ISSUE THREAD

**Issue by alexzicat** [faceyspacey/react-universal-component#10]
First of all, great job !
You've done amazing work 👍 

I'm having trouble with the rendering of my universal component on the server.
The _**Loading**_ component is always rendered by **_ReactDOM.renderToString_** instead of doing it synchronously. The **_flushChunks_** and **_flushModuleIds_** are working just fine. 

When I access my page I have the "...checksum invalid" error because the client bundle renders the component and not the **_Loading_** one.

Do you have an idea what might be causing my component to be rendered async on the server ?

server : https://github.com/alexzicat/react-async-ssr/blob/master/server/index.js
webpack client : https://github.com/alexzicat/react-async-ssr/blob/master/webpack.client.js
webpack server : https://github.com/alexzicat/react-async-ssr/blob/master/webpack.server.js

**Comment by chrisblossom** [comment]
Thanks for putting up an example repo, very helpful!

Here is the commit I went through until I solved the issue:
https://github.com/chrisblossom/react-async-ssr/commit/4fe406e9de95c8e1be8fbf08523f3beedad4b09c

The only change that was actually needed was inside your server's Webpack plugin config, you are missing:
```js
new webpack.optimize.LimitChunkCountPlugin({
  maxChunks: 1,
}),
```
https://github.com/chrisblossom/react-async-ssr/commit/5d10cb3b86b610ce2614128c67b580a92c558ea0

We should probably add this to the docs. @faceyspacey thoughts?

**Comment by faceyspacey** [comment]
excellent work @chrisblossom thanks so much for being so helpful! ...ur PR is on point. I merged it. yea, some info didnt make it over from flush chunks and probably should be in both. 

@alexzicat glad ur likin the setup ...make sure u give this a try by the way:

https://github.com/faceyspacey/redux-first-router-demo

**Comment by alexzicat** [comment]
Everything is working great with the added plugin.
Thanks !

@faceyspacey, I'll check redux-first-router for sure ;)

**Comment by kimjuny** [comment]
chrisblossom saved my day!
