### ISSUE TITLE
How to force synchronous resolution of wrapped components?

### ISSUE THREAD

**Issue by forabi** [faceyspacey/react-universal-component#103]
I'm trying to write integration tests using Jest for a web app which uses `react-universal-component`, Redux and React Router.

I'm using a webpack configuration to build a bundle of the app specifically for testing.

I'm having a lot of issues testing asynchronous actions. My approach to testing is to create the app tree and provide a store instance:

  ```typescript
  const { store } = createConfiguredStore({
    history,
    dependencyOverrides: {
      getResponseForDataRequest,
    },
    additionalMiddleware: [
      logActionsObserver,
    ],
  });

  const tree = (
    <HelmetProvider>
      <Provider store={store}>
        <ConnectedRouter history={history}>
          <App />
        </ConnectedRouter>
      </Provider>
    </HelmetProvider>
  );

  const wrapper = mount(tree);
  ```

Where `<App />` looks like this:

  ```typescript
  <div className={cc([classes.root, { 'no-js': !hasMounted }])}>
    <div className={classes.view}>
      <Switch>
        <Route path="/search" component={LoadableSearchResults} />
        <Route path="/about" component={LoadableAbout} />
        <Route path="/privacy-policy" component={LoadablePrivacyPolicy} />
        <Route path="/:slug" component={LoadableNotablePerson} />
        <Route component={LoadableHome} />
      </Switch>
    </div>
  </div>
  ```

The `Loadable*` components are `UniversalComponent`s.

I then wait for a specific action to be dispatched and make assertions.

The problem is that when I render the test tree, all I get is `Loading...` in place of loadable components.

Replacing the loadable components in `<App />` with the actual pages does the trick. But I don't want to maintain two separate versions of `<App />` (one for testing and the other for production).

Is there a Webpack config or something I can use to force `react-universal-component` to always load the wrapped components _synchronously_ so I can test the components?

**Comment by faceyspacey** [comment]
I’m on my phone now but check the tests of the repo itself.

Probably the correct solution is to use a mock so that universal always finds the component synchronously. Search in the code for how required are made in different environments. You probably want to mock the way it’s done on node outside of webpack.

**Comment by faceyspacey** [comment]
It’s also likely thinking it’s on th client because thebjest environment mocks clients. So you may want to mock the isServer function to return true and the isWebpack function to return false so that a synchronous node require occurs.

**Comment by forabi** [comment]
> It’s also likely thinking it’s on th client because the jest environment mocks clients.

Yeah that's what I thought.

> So you may want to mock the isServer function to return true and the isWebpack function to return false so that a synchronous node require occurs.

I actually tried to mock `isServer` to always return `true`, but missed `isWebpack` :smile:. Thanks! I'll try this and report back!

**Comment by forabi** [comment]
No luck. Should `react-universal-component` be bundled with webpack or left as an external package?

**Comment by faceyspacey** [comment]
Bundled for your tests? You don’t wanna do that in jest. There shouldn’t be any webpack.

Take a look at the tests in this repo.

**Comment by forabi** [comment]
I mentioned that I'm bundling the app for Jest using webpack. I know it's not the standard way to use Jest but I was thinking it might save me some code duplication and maintenance overhead because I won't have to mirror the globals and loader configurations in Jest.

**Comment by faceyspacey** [comment]
I wish I had the solution off hand for you, but given you're bundling with webpack for the tests it's a little bit more complex. Mocking `universal` to just render and snapshot the component and props passed along is always an option.

**Comment by forabi** [comment]
Thanks for your help! `react-universal-component` is awesome! I'll most probably end up mocking `universal` like you said.
