### ISSUE TITLE
chunk not available for synchronous require yet

### ISSUE THREAD

**Issue by mvoica** [faceyspacey/react-universal-component#104]
Disclaimer: I'm a newbie.
As for the issue:
In one of my files, I'm doing: 
const LazyHomePage = universal(import(/* webpackChunkName: "homeComponents" */ '../homeComponents'), {})

I'm using a client webpack (v.3.10 btw) config, and a separate server webpack config (for ssr), which has  

new webpack.optimize.LimitChunkCountPlugin({
      maxChunks: 1
    }),

in the plugins. From the point of view of the generated files, I get main.client.js, homeComponents.js, homeComponents.css, from the client compilation, and main.server.js and main.server.css from the server compilation (as expected).

I'm using the extract-css-chunks-webpack-plugin and the babel-plugin-universal-import

The compiled universal import code (from the server bundle) looks like this:

var LazyHomePage = __WEBPACK_IMPORTED_MODULE_5_react_universal_component___default()(__WEBPACK_IMPORTED_MODULE_2_babel_plugin_universal_import_universalImport___default()({
  id: '../homeComponents',
  file: '... redacted ...',
  load: function load() {
    return Promise.all([new Promise(function(resolve) { resolve(); }).then(__webpack_require__.bind(null, /*! ../homeComponents */ 139)), __WEBPACK_IMPORTED_MODULE_1_babel_plugin_universal_import_importCss___default()('homeComponents', {})]).then(function (proms) {
      return proms[0];
    });
  },
  path: function path() {
    return __WEBPACK_IMPORTED_MODULE_0_path___default.a.join(__dirname, '../homeComponents');
  },
  resolve: function resolve() {
    return /*require.resolve*/(/*! ../homeComponents */ 139);
  },
  chunkName: function chunkName() {
    return 'homeComponents';
  }
}));

seems the resolve function knows the fact that the required module is in the same bundle.

now let's look at the universal component (index file): 
Since the babel-plugin-universal-import is used, the setHasBabelPlugin() is called in universal. Therefore, the options.isDynamic will always be true.
Therefore, when the requireUniversalModule is initialized in 'componentWillMount', it will do a 
getConfig(isDynamic, universalConfig, options, props); And isDynamic is true. 
At this point in time, the getConfig will return the universalConfig, which is not a function (it's the object webpack generated for the import(...)). It happens that this object has a path() function.
In the requireSync, the requireUniversalModule, will try to load the homeComponents module by the path(), which fails.
If the homeComponents were loaded by the resolve function (2 lines below), it would be found.

So... now the question is: 
1. am I using the parts in a wrong way? 
2. if not: I was hoping that the extra options passed to the universal() -> as the 2nd argument, would overrule things (i.e. the getConfig would allow me to overrule the resolve, or the path, chunkName, etc. on the server bundle). Also, can the tryRequire via resolve be tried if the tryRequire via path fails?

Oh, and super fantastic work btw - the least-opinionated ssr example I could understand.

**Comment by emphaticsunshine** [comment]
@faceyspacey , I am also facing a similar issue where `dynamicImport` is coming as `false` and as a result `getConfig` function returns `default` object.

**Comment by faceyspacey** [comment]
Hey guys, glad you're diving into the *Universal* set of tools. I'm very limited on time currently, but the answers are in the repo issues, and on gitter. @emphaticsunshine your problem can be solved. I believe @tannerlinsley recently had your exact problem. Maybe he can provide some advice.

**Comment by skk2142** [comment]
Any update on this?

**Comment by ScriptedAlchemy** [comment]
@skk2142 @mvoica @emphaticsunshine upgrade all universal family and switch to webpack 4. See if this goes away.
