### ISSUE TITLE
Breaks Webpack compile when import has more than 1 variable

### ISSUE THREAD

**Issue by Grsmto** [faceyspacey/react-universal-component#107]
Hi @faceyspacey !
First thanks for the work, still pretty happy with my setup RFR.

I just spent hours trying to debug this, my tests files were being compiled in my bundle, breaking everything. I finally figured out it was coming from the `import` declaration of universal component:
```
const UniversalComponent = universal(
  ({ path = 'pages', page }) => import(`../../${path}/${page}`)
);
```

It seems like if i use 2 variables in the `import`, Webpack will get in a black hole and compile every JS files of my project. Weirdest thing is that the code is not even called at run-time, so this is a compilation time issue.
I know it's not a precise report but really I have no idea why this is happening.

**Comment by faceyspacey** [comment]
Glad you like RFR, big stuff coming very soon.

..That's how webpack works. You can use the following plugin to filter the files just to the ones that behave as entries for chunks:

https://webpack.js.org/plugins/context-replacement-plugin/

Or insure the folders used only have the entry files.

**Comment by faceyspacey** [comment]
search through some of the issues in my repos where i mentioned the context replacement plugin--others have posted their successful usage of it.
