### ISSUE TITLE
Can't renderd current Component when debugging in visual studio code(also use typescript)

### ISSUE THREAD

**Issue by MrKou47** [faceyspacey/react-universal-component#110]
First of all,this repo save me from the react ssr(used react-router v4!😢),thank a lot!
But when i try to rebuild my project use typescript,i find that i couldn't render my component at server side. It seems that the AsyncComponent(like `export const AsyncHome = universal(import('./container/home')`) doesn't load at the server.
Emmm.. and i also try to debug my project in the Visual Studio Code, use the debug tool.

Here's some imporment code:

```tsx
// HomeComponent.tsx
import * as React from 'react';
import { connect } from 'react-redux';

import { getUserList, toogleBlankVisible } from './action';

import styles from './home.css';

export function getInitialData(dispatch) {
  return dispatch(getUserList());
}

class Home extends React.Component<any, any> {
  constructor(props) {
    super(props);
  }

  componentDidMount() {
    getInitialData(this.props.dispatch);
  }

  handleBtnClick = () => {
    const { dispatch } = this.props;
    dispatch(toogleBlankVisible());
  }

  render() {
    const { list, blankVisible, dispatch } = this.props;
    const userListDOM = list.map((v, i) => <span key={i}>name: {v.name}</span>);

    return (
      <div className={styles.red}>
      <span>Hello</span>
      <div>
          {userListDOM}
        </div>
        <button onClick={this.handleBtnClick}>toggle blank</button>
        {blankVisible ?
          <div className={styles.blank}>blank</div>
          : null}
      </div>
    );
  }
}

(Home as any).title = 'home page';
(Home as any).getInitialData = getInitialData;

const mapState2Props = store => {
  return { ...store.home };
};

export default connect(mapState2Props)(Home);
```
and i am using `react-router-config`,so my `router.js` is:
```js
// client/routes.js
import * as React from 'react';
import universal from 'react-universal-component';

import AppRoot from './container/root';

const UniversalHome = universal(() => import('./container/home'), {
  resolve: () => require.resolveWeak('./container/home'),
  chunkName: 'container/home',
  minDelay: 500,
});

const routes = [
  {
    path: '/',
    exact: true,
    component: AppRoot
  },
  {
    path: '/home',
    component: UniversalHome,
  },
];

export default routes;
```
and my render function is(server side):
[render.tsx](https://github.com/MrKou47/react-ssr-example/blob/typescript/src/server/utils/render.tsx)
at this section, code has something wrong at:
```ts
   // I'm trying to receive all dataInitial function from currentComponment,for trying to do this work,i'm call renderToString method before this code.
    const promiseList = routeBranch.map(({ route }) => {
      const component: any = route.component;
      const noop = Promise.resolve();
      const { WrappedComponent } = component; // I can't get WrappedComponent at this line. it alway be UniversalComponment..😕
      if (WrappedComponent && WrappedComponent.getInitialData) {
        return WrappedComponent.getInitialData(dispatch);
      }
      return noop;
    });
```

Other tips:

I'm alway use `css-modules-require-hook` to achieve load css at the runtime(because i'm use VS Code to debug my project).
> const hook = require('css-modules-require-hook');
hook({
  generateScopedName: '[name]-[local]-[hash:base64:5]',
});

And my `launch.json` is:
```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Current TS File",
      "type": "node",
      "request": "launch",
      "args": [
        "${relativeFile}"
      ],
      "runtimeArgs": [
        "--nolazy",
        "-r",
        "ts-node/register"
      ],
      "env": {
        "NODE_ENV": "development",
      },
      "sourceMaps": true,
      "cwd": "${workspaceRoot}",
      "protocol": "inspector",
    }
  ]
}
```

When i want to debug my project,i will open the `server.ts` file and then start the debug program.

Now my Component renderd on the chrome just some text: `Error: export not found ` and i don't know why..
I guess it might that ts-node can't compile the `import()` method, and `babel-plugin-universal-import` couldn't run in the ts runtime. And i also tried [typescript-and-non-babel-environments](https://github.com/faceyspacey/babel-plugin-universal-import#typescript-and-non-babel-environments),but it also couldn't fix my problem..
![text](https://preview.ibb.co/gLPJ0H/DX_20180316_2x.png)

**Comment by ScriptedAlchemy** [comment]
Looks related to aggressive code splitting in webpack 3? or a miss configuration of the chunking.

Might wanna give webpack 4 a shot. Major updates across most of universal... might fix your issue?

**Comment by nikopavlica** [comment]
If I understand your problem correctly, then https://github.com/faceyspacey/react-universal-component#preload should have it all covered.

To sum up, either use
```
route.component.preload().then(WrappedComponent => {
    // do something with WrappedComponent
});
```
or
```
const WrappedComponent = route.component.preloadWeak();
if (WrappedComponent) { 
    // do something with WrappedComponent
}
```
before doing `React.renderToString()`

**Comment by EdonGashi** [comment]
@nikopavlica has the right answer. I needed something similar to access statics from the server. preload() does not execute in the same javascript frame so you won't have the inner component immediately for synchronous rendering.

Change this line:
```js
const { WrappedComponent } = component; // I can't get WrappedComponent at this line. it alway be UniversalComponment..
```
to this:
```js
const WrappedComponent = component.preloadWeak();
```

Because you are in the server you don't need to wait any promise and `preloadWeak` will always return your desired result (if other conditions are met).
