### ISSUE TITLE
QUESTION: react-universal-component with DllPlugin

### ISSUE THREAD

**Issue by yoshi95** [faceyspacey/react-universal-component#111]
Hi, i apologize if this was asked before (i tried searching for related keywords in issues but nothing came up, only this looks remotely relevant https://github.com/asfktz/autodll-webpack-plugin/issues/23)

**Setup**
split out multiple bundles with DllPlugin
- `react-universal-component` in `vendor` dll 
- have a `core-components` bundle (built with different webpack config) that uses the `vendor` dll file

**Issue** (Client Side)
the `core-components bundle` uses `react-universal-component` from `vendor bundle`
- all dynamic chunks loaded successfully, `React.hydrate` kicks in
- `vendor bundle` has it s own `__webpack_require.m`, and cannot resolve the component in `core-components bundle` in a synced manner (`__webpack_require.m[weakId]` fails to resolve)
- this causes `react-universal-component` to render the `<Loading />` component and re-renders the dom

**Question**
what is the proposed setup (if possible) that will work with DllPlugin when components are split between multiple webpack builds. 
- and have all vendor files in it s own vendor chunk (like react-universal-component)

NOTE: everything works when it s built with 1 single webpack config, no issues there

thanks

**Comment by ScriptedAlchemy** [comment]
Best bet would be to use externals, Create a map of what is provisioned by another build and use them as web pack externals in your current one. It's not the ideal solution - I know - but its a way to use vendor code from another bundle. 

I DO have a plan to create a new utility which will automatically allow webpack builds to share any modules they own. Mostly working as one build in the FE. It's not much work actually, but there's no time right now to look into that.
