### ISSUE TITLE
When using SSR, avoid loading and rendering on client-side

### ISSUE THREAD

**Issue by kirittanna** [faceyspacey/react-universal-component#114]
We use SSR and everything works as expected ... however, on the client side when the chunks are loading ... the component switches to the loading state to render the loader. 

This results in the following:
1. Page renders with SSR HTML
2. Client side rendering starts ... Page renders Loading HTML
3. Same HTML from #1 is rendered (after chunk loads)

Whats the best way to eliminate step #2 above?

**Comment by Arturszott** [comment]
To avoid that you have to serve JS scripts for all chunks that were used to render server side components. Load all chunks before you run your app scripts and everything should be okay. https://github.com/faceyspacey/react-universal-component#flushing-for-ssr

**Comment by kirittanna** [comment]
@Arturszott thanks for your reply.

Solved! the loading showed up as the chunk wasn't being loaded synchronously. Best way to debug is examine what is the output of **scripts** when using _flushChunks_.
In the end it turned out to be the wrong import.

Was using (incorrect) -
`import { flushChunks } from 'webpack-flush-chunks';`
Instead of (correct) -
`import flushChunks from 'webpack-flush-chunks';`

First load is synchronous and rest loads async. 
Thanks @faceyspacey for building and sharing this great set of tools! 👍

**Comment by faceyspacey** [comment]
glad you guys found the solution. Thanks @Arturszott for the assistance.
