### ISSUE TITLE
Difficulty setting up universal component unit tests with jest/enzyme

### ISSUE THREAD

**Issue by hedgepigdaniel** [faceyspacey/react-universal-component#116]
I'm not sure how you've setup the tests in this repository, but I ran into a few issues while setting them up with jest/enzyme.

Here is a repository [demonstrating](https://github.com/hedgepigdaniel/ruc-jest-repro) the issues. You can run the tests with `yarn run test`.

On the `master` branch, everything works. This is using a combination of `babel-plugin-syntax-dynamic-import` and https://github.com/adierkens/babel-plugin-dynamic-import-promise, but not `babel-plugin-universal-import`.

On the `universal-import` branch, there are three commits where the tests do not work, where I tried using various combinations of `babel-plugin-universal-import` and `babel-plugin-dynamic-import-node`.

One error:
```
TypeError: moduleName.split is not a function

    
      
      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:154:30)
      at Object.<anonymous> (testloadable.jsx:25:74)
```

Another:
```
TypeError: /home/daniel/openlearning/ruc-jest-repro/testloadable.jsx: Property value expected type of string but got null
      
      at Object.validate (node_modules/babel-types/lib/definitions/index.js:161:13)
```

Is this package meant to work with jest using the documented setup with `babel-plugin-universal-import?

**Comment by faceyspacey** [comment]
And is mocking RUC not an option for you? Otherwise, following the tests of this package should provide some guidance.
