### ISSUE TITLE
[question] webpack 4 +  ssr + webpack-hot-middlewar

### ISSUE THREAD

**Issue by vasivas** [faceyspacey/react-universal-component#118]
react-universal-component will work in conjunction - `webpack 4`,`webpack-dev-middleware`,`webpack-hot-middleware`,`webpack-hot-server-middleware`,`ssr`, `ccs imported in js`?

**Comment by faceyspacey** [comment]
yes, but the commons chunk configuration is different in webpack 4. i'm not exactly sure what it is, but other developers have figured it out. There should be info in one of the related repos' closed issues.

If you find it, please paste it here.

**Comment by vasivas** [comment]
@faceyspacey https://github.com/faceyspacey/react-universal-component/issues/113 this question?

`react-universal-component` needs MiniCssExtractPlugin?

**Comment by faceyspacey** [comment]
exactly, well done!

...you have to use style-loader during development for webpack 4. mini doesn't work (last i checked) in dev.

**Comment by vasivas** [comment]
> ...you have to use style-loader during development for webpack 4. mini doesn't work (last i checked) in dev.

MiniCssExtractPlugin if not, then who makes .css in separate chunks?I have dynamic routs and everyone has their own .css.When mounting the router I add .css in the dom, and remove when unmount.   If the dev chunk will not be the difference in the logic of the dev and prod will be great.

**Comment by faceyspacey** [comment]
i know, thats what i did with extract-css-chunks-webpack-plugin in the past. you could use it during dev with HMR. you can use webpack 3 still. otherwise, in dev style-loader brings you all the css you need, and you dont send the stylesheets chunks from the server.

**Comment by vasivas** [comment]
> otherwise with wp4, in dev style-loader brings you all the css you need, and you dont send the stylesheets chunks from the server.

wb4 generated code for dynamic import append in head <link> with blob   which leads to overlapping styles, since I can't delete them, their names are generated dynamically.in theory   can get out of the situation, but it will be programming on webpack, not on js.

**Comment by Bram-Zijp** [comment]
I currently use https://github.com/shepherdwind/css-hot-loader  with mini css extract plugin while developing. I do however use a React Loadable fork but it should work for react universal component.

**Comment by vasivas** [comment]
@Bram-Zijp 
1) you use in project `server-side-render`?
2) `css-hot-loader` use without `webpack-dev-middleware` and `webpack-hot-middleware`?

**Comment by zackljackson** [comment]
I’ve implemented this and it’s available to beta test. 
Currently working, just needs more tests and finished docs 

@vasivas
