### ISSUE TITLE
Static hoisting should be configurable and disabled by default when using dynamic imports

### ISSUE THREAD

**Issue by nikopavlica** [faceyspacey/react-universal-component#121]
When I import a component with
```
const UniversalComponent = universal(props => import(`./pages/${props.page}`))
```
the `UniversalComponent` will eventually end up with static properties from all the sub-pages. This behaviour caused some really hard-to-catch bugs in my app and I think it would be better if hoisting would be both:
- configurable via options
- disabled by default when dynamic imports are used (although this would be breaking change)

Any thoughts?

**Comment by faceyspacey** [comment]
An option to turn it off would work
