### ISSUE TITLE
How would universal play with react / redux / rfr stack?

### ISSUE THREAD

**Issue by ferborva** [faceyspacey/react-universal-component#123]
**General question here.** How well would the universal component play with a react / redux / redux-first-router stack and how much effort could it take to integrate?

**Comment by ScriptedAlchemy** [comment]
Dead easy my man! In fact, RFR Uses RUC as part of its total implementation. 
Bear in mind, this demo needs WP4 updating, and right now I am working on the Universal Demo (without RFR)

https://github.com/faceyspacey/redux-first-router-demo
