### ISSUE TITLE
Migrate to React 16.x API

### ISSUE THREAD

**Issue by re6exp** [faceyspacey/react-universal-component#129]
See [Component Lifecycle Changes](https://reactjs.org/blog/2018/03/29/react-v-16-3.html)
And [schema](https://twitter.com/dan_abramov/status/981712092611989509).

**Comment by jussikinnula** [comment]
I will most probably work on this (during next three weeks), unless someone else already started to do this.

**Comment by ScriptedAlchemy** [comment]
pull requests <3

**Comment by ScriptedAlchemy** [comment]
@re6exp @jussikinnula any of you have some time to assist with this? :)

**Comment by re6exp** [comment]
Now I have some time to look at this by myself!

**Comment by re6exp** [comment]
Done. Tests are passed. Checking before PR.

**Comment by MartinCerny-awin** [comment]
This can be closed as it is merged @re6exp

**Comment by ScriptedAlchemy** [comment]
@re6exp great work on this, its finally merged
