### ISSUE TITLE
Component rendering for SEO

### ISSUE THREAD

**Issue by manish4781** [faceyspacey/react-universal-component#130]
Hi,
i am trying to render my component on server, a component which fetches the data from another 3rd party API on **componentDidMount**, my component is rendering fine but when is pass the string returned from **ReactDOM.renderToString** to my **.ejs** file which is missing the data returned from 3rd party API 

```
import React from 'react';
import ReactDOM from 'react-dom/server';
import { flushChunkNames } from 'react-universal-component/server';
import flushChunks from 'webpack-flush-chunks';

import App from '../shared/App';
import HorizontalModule from '../shared/Horizontal-module';
export default ({ clientStats }) => async (req, res) => {
    const app = (
        <App/>
    );
 
    const appString = ReactDOM.renderToString(app);
    const chunkNames = flushChunkNames();
    const { js, styles, cssHash } = flushChunks(clientStats, { chunkNames });
    res.render('index', {
        appString,
        js,
        styles,
        cssHash
    });

    console.log(appString);
};

```
my <App> component is rendering fine, but when is see the view-source of a page component is empty.
**appString** is basically empty

currently my code for fetching data from API written in componentDidMount but i have tried componentWillMount as well

**Comment by eliseumds** [comment]
So `chunkNames` is empty? Can you share your Webpack config (for the server)?

**Comment by manish4781** [comment]
this is where my component rendered http://ec2-13-232-170-86.ap-south-1.compute.amazonaws.com:3000/

and this is my code base https://github.com/sharmam1/testproj

**Comment by ScriptedAlchemy** [comment]
componentDidMount doent run on a server
