### ISSUE TITLE
Possible to use this with asp.net C#?

### ISSUE THREAD

**Issue by MartinDawson** [faceyspacey/react-universal-component#131]
I use C# asp.net for the backend and not Node.js.

Does this library and [webpack-flush-chunks](https://github.com/faceyspacey/webpack-flush-chunks) work for this or do I need something else?

**Comment by ScriptedAlchemy** [comment]
I don't think so. However, there is a way in which you can POST the data to an internal render service inside a dockerized container. That way, the rendering takes place internally and you can use the C# asp system as the render layer/gateway. 

Render Service <-> Monolith  <-|-> Ingress <-> Public
