### ISSUE TITLE
Unable to find x in Webpack chunks. Please check usage of Babel plugin.

### ISSUE THREAD

**Issue by luangjokaj** [faceyspacey/react-universal-component#137]
After upgrading from 2.9.0 to 3.0.0 I get this error:

`[FLUSH CHUNKS]: Unable to find Views-Home in Webpack chunks. Please check usage of Babel plugin.`

Everything works correctly on the 2.9.0. 
You can check the code here: https://github.com/luangjokaj/react-ssr-boilerplate

All the dependencies are up to date except react-universal-component.

**Comment by cdebotton** [comment]
I'm running into the same issue. Looking at the compiled code, it looks like yields the following transformation:
```jsx
const Login = universal(import('./Login'));

// into

const Login = (0, _reactUniversalComponent.default)((0, _universalImport2.default)({
  id: "./Login",
  file: "/Users/user/Projects/app/.tmp/ts/app/src/index.js",
  path: () => _path2.default.join(__dirname, './Login'),
  resolve: () => require.resolveWeak('./Login'),
  chunkName: () => "Login"
}));
```

`webpack-flush-chunks` throws that error here in [flushChunks.js](https://github.com/faceyspacey/webpack-flush-chunks/blob/master/src/flushChunks.js#L211).

```jsx
  const result = !!(assets[entry] || assets[`${entry}-`])
  if (!result && checkChunkNames) {
    console.warn(
      `[FLUSH CHUNKS]: Unable to find ${entry} in Webpack chunks. Please check usage of Babel plugin.`
    )
  }
```

This method is invoked shortly after [here](https://github.com/faceyspacey/webpack-flush-chunks/blob/master/src/flushChunks.js#L233).

```jsx
  chunkNames
    .reduce((names, name) => {
      if (!hasChunk(name, stats.assetsByChunkName, checkChunkNames)) {
        return names
      }
```

However, looking at the output of my stats.json, `assetsByChunkName` only contains the entry bundle.

```json
  "assetsByChunkName": {
    "main": "bundle.js"
  },
```

And then other chunks are listed under `assets`:

```json
 "assets": [
    {
      "name": "bundle.js",
      "size": 2309495,
      "chunks": [
        "main"
      ],
      "chunkNames": [
        "main"
      ],
      "emitted": true
    },
    {
      "name": "0.bundle.js",
      "size": 861184,
      "chunks": [
        0
      ],
      "chunkNames": [],
      "emitted": true
    },
    {
      "name": "1.bundle.js",
      "size": 8086,
      "chunks": [
        1
      ],
      "chunkNames": [],
      "emitted": true
    }
  ],
```

Interestingly, the chunk name that is being looked up doesn't even match the listed names in my `assets` object. Maybe something changed in how webpack outputs `stats.toJson()`? (I'm on `4.16.0`).

**Comment by GuillaumeCisco** [comment]
I experiment the same issue. I'm using webpack `4.16.1` but tested with webpack `4.15.1` and the same behavior happens.

**Comment by ScriptedAlchemy** [comment]
Ill investigate this further

**Comment by luangjokaj** [comment]
@ScriptedAlchemy any solution?

**Comment by giankotarola** [comment]
I have the same error but with dynamic imports 😞

**Comment by ScriptedAlchemy** [comment]
Usually related to a Babel mismatch. 

Make sure you are on the latest of all faceyspacey dependencies. 

Make sure you are including RUC in the webpack build if using externals. 

Check the RUC and Babel plugin readme as new options to help people stuck with this issue are there

**Comment by ScriptedAlchemy** [comment]
Going from 2 to 3, this issue is very old. Best I can suggest is double check our readmes, the universal demo. 

If ur really stuck, I’ll send you one of my own systems - it’s not completed but it’ll run and you can either do it like that, or use it and clean it up a little

**Comment by ScriptedAlchemy** [comment]
Make sure you are providing enough stats to flush chunks. If you are only outputting some, it’ll not resolve anything. 

Make ur stats as verbose as possible

**Comment by giankotarola** [comment]
@ScriptedAlchemy Thanks! It fixed using https://github.com/faceyspacey/babel-plugin-universal-import

**Comment by luangjokaj** [comment]
I have all these checked and still getting the same thing 😞
If I downgrade to v.2.9.0 it works!

**Comment by ScriptedAlchemy** [comment]
Can you matey wiping out any lock files and node modules. Sometimes it gets stuck. Try manually running yarn add on the dependencies to ensure they are up to date. If you send me a repo, I’ll look at the issue personally

**Comment by MartinCerny-awin** [comment]
I am having exactly the same issue. My CSS are also not correctly loaded initially, they get loaded later by client code.

**Comment by ScriptedAlchemy** [comment]
I’ll try and look at this today. I know this issue is because slashs are coming out in the output, well usually anyways. It might be Babel 7

**Comment by MartinCerny-awin** [comment]
Yes, I have all Babel up to date.

**Comment by ScriptedAlchemy** [comment]
Don’t use strings. Use an import function there. I’ll send the code later. Or.... look at my demo and see how I use RUC. 
 You can’t resolve slash names. So if you use a slash. I designed it to fail

**Comment by GuillaumeCisco** [comment]
I get the error when I build my application in production mode.
Curiously, it works well in development mode.

I will try to provide an example project, I'm waiting for others to have the same issue.
Otherwise, though there is a warning, the application works very well :)

**Comment by ScriptedAlchemy** [comment]
make your own universal component


```import React from 'react'
import PropTypes from 'prop-types'
import universal from 'react-universal-component'
import Loading from './components/Loading'
import Err from './components/Error'

// needs error handling
const determineHowToLoad = props => typeof props.component !== 'string'
  ? props.component()
  : import(`./${props.component}`)

/**
 *
 * @type {universal.UniversalComponent<any>}
 * @param props - the props from the JSX component, these will be passed into the component as well
 * props on the JSX component can include any of the universal components props as well, like onLoad, onError, error, timeout...
 */
const UniversalComponent = universal(determineHowToLoad, {
  minDelay: 500,
  loading: Loading,
  error: Err,
})

// PropTypes so people know what they can use & so nobody passes shit that will break universal
// Ive already forked the open source project so create something that i can extend / PR new features back to the community. Depending on the requirements. I might maintain both a repo at fiverr and on my personal repo where i can make more drastic changes which might not be beneficial to fiverr
UniversalComponent.propTypes = {
  loading: PropTypes.oneOfType([
    PropTypes.func,
    PropTypes.element,
    PropTypes.bool,
  ]),
  error: PropTypes.oneOfType([
    PropTypes.func,
    PropTypes.element,
    PropTypes.bool,
  ]),
  key: PropTypes.oneOfType([PropTypes.string, PropTypes.func]),
  timeout: PropTypes.number,
  onError: PropTypes.func,
  onLoad: PropTypes.func,
  minDelay: PropTypes.number,
  alwaysDelay: PropTypes.bool,
  loadingTransition: PropTypes.bool,
}

const loadComponent = file => universal(determineHowToLoad({ component: file }), {
  // eslint-disable-line no-unused-vars
  minDelay: 500,
  loading: Loading,
  error: Err,
})
export default UniversalComponent
export { loadComponent, universal }
```



![image](https://user-images.githubusercontent.com/25274700/47261609-9b8a3680-d487-11e8-9453-55d1d29a24e7.png)

**Comment by luangjokaj** [comment]
Any work around for the issue I'm having on the latest version 3.0.3 (with Babel 7)? Im still on 2.9.0 😞

**Comment by ScriptedAlchemy** [comment]
Check the demo. Makes sure the configuration match. Worst case. Paste your project in.

**Comment by luangjokaj** [comment]
@ScriptedAlchemy I'm using Babel 7, the rest of the configuration is same as in the demo.

Code: https://github.com/luangjokaj/react-ssr-boilerplate

**Comment by MartinCerny-awin** [comment]
I am using imports with slash and it fails.

Is this not supposed to work? page prop is always string without slashes. 
```
const UniversalComponent = universal(props => import(`async/${props.page}`), {
  onError,
});
```

I think that my setup is really similar to react-ssr-boilerplate as that boilerplate and my code is mostly based on the demo.

I do not really remember the purpose why I had to create async folder as it is more than one year ago. I think that it was probably for webpack to generate these chunks.

**Comment by ScriptedAlchemy** [comment]
I would suggest uninstalling all faceyspacey products. Then reinstalling them. 


Re-read documentation around the Babel plugin and flush chunks and RUC. 

There’s ways to enable it disable things regarding the chunks naming. I’d also suggest yarn linking the code, especially the flush chunks problem and see if your webpack output is providing enough data for the resolution to take place 

Worst case you can manually use the universal HOC and create your own chunk names. I am working on a new demo, built on Babel 7 with all dependencies up to date.

**Comment by luangjokaj** [comment]
@ScriptedAlchemy `ignoreBabelRename` did the trick, finally! 🎉

**Comment by ScriptedAlchemy** [comment]
:) make sure all the chunks are there, usually those stupid some~chunk~name.js that webpack makes wont work because it cant be resolved. 

Flush chunks needs a little fine tuning, so if its giving you issues, ill prioritize your PRs.

**Comment by GuillaumeCisco** [comment]
Exact issue as https://github.com/faceyspacey/react-universal-component/issues/148
By the way the issue still exists for me in production, the chunks are not generated but are listed by flush chunks. I will open a new issue with detailed information.

**Comment by ScriptedAlchemy** [comment]
It might be best to just open up flush chunks and create a PR that solves your problem :P open an issue with a repo and I can try to look

**Comment by MartinCerny-awin** [comment]
`ignoreBabelRename` solved the issues for me as well. Everything works perfectly as before. Thank you!
