### ISSUE TITLE
Webpack 4.16.2 - Critical dependencies - the request of a dependency is an expression

### ISSUE THREAD

**Issue by lorenzomigliorero** [faceyspacey/react-universal-component#139]
With Webpack 4.16.2 this import cause a critical dependencies warning:
`import universal from 'react-universal-component'`

With Webpack 4.8.0 works fine.
I suppose this is the cause:

https://github.com/webpack/webpack/releases/tag/v4.16.2
_**handle module.require like require**_

In [utils.js](https://github.com/faceyspacey/react-universal-component/blob/58ca92b47d209da63bff713c53e70312eaf34e5b/src/utils.js#L41) i found a `module.require`.

Can you investigate about this?
Thanks for your work!

**Comment by lorenzomigliorero** [comment]
I confirm that the last Webpack working version is the `4.16.1`

**Comment by rashtay** [comment]
I am facing the same issue.

https://stackoverflow.com/questions/51519892/critical-dependency-the-request-of-a-dependency-is-an-expression-react-unive#51546626

**Comment by luangjokaj** [comment]
Same issue here... 🙄

**Comment by digitalkaoz** [comment]
same here, wont work with webpack@4.17.1, can confirm it works with 4.16.1 but downgrading is not an option.

**Comment by phips28** [comment]
same for me. 4.16.1 works

**Comment by ivan-aksamentov** [comment]
Guys, if this warning (especially the word "critical" in it) makes you nervous, try this workaround:
https://github.com/ivan-aksamentov/reactlandia-bolerplate-lite/issues/5#issuecomment-413306341
I find it very comforting :)

**Comment by hedgepigdaniel** [comment]
This fixes the easy part (the one in `babel-plugin-universal-import`): https://github.com/faceyspacey/babel-plugin-universal-import/pull/67

Not sure where to start with the one coming from RUC.

**Comment by cdoublev** [comment]
I fixed the same warning as mentioned in this issue, but which was throwing from [RUC/src/utils.js](https://github.com/faceyspacey/react-universal-component/blob/master/src/utils.js#L51), by following your PR. Is it what you were looking for? Sorry if I'm totally off topic. It's been a few months that I didn't seriously wrap my head around SSR and those great URC/RFR packages.

**Comment by hedgepigdaniel** [comment]
@cdoublev you fixed it? make PR pls :fork_and_knife: :smile:

**Comment by ScriptedAlchemy** [comment]
Yeah please open a PR or past the code snippet, happy to update

**Comment by ScriptedAlchemy** [comment]
We might be able to work around it by treating as a string 

‘let Module = require(`${url}`);’

**Comment by ScriptedAlchemy** [comment]
Lol it worked. All warnings are gone. Releasing a beta and opening a PR. In the next few hours. Will appreciate a few guys who can confirm the error is gone

**Comment by ScriptedAlchemy** [comment]
Please try installing `3.0.2-beta.0`

If it works for you, ill merge and release

**Comment by loganfromlogan** [comment]
I was getting this error as well. Installing `3.0.2-beta.0` fixed it. Thank you :)

**Comment by ScriptedAlchemy** [comment]
Yaaaaay! 

Okay I’ll merge it tonight or tomorrow. 

Heads up, there’s a React 16 rewrite on the way. It will be RUC 4 but I plan to support RUC 3 for a while ❤️

 Thrilled these damn errors are gone.

**Comment by volkanunsal** [comment]
I just upgraded. I'm getting this warning now with webpack 4.18.0.

```
WARNING in ./node_modules/react-universal-component/dist/index.js.flow 7:12
Module parse failed: Unexpected token (7:12)
You may need an appropriate loader to handle this file type.
```

The warnings only go away if I specify the load path as `index.js` in the following manner:

```js
import universal from 'react-universal-component/dist/index.js';
```

**Comment by ScriptedAlchemy** [comment]
okay hold on

**Comment by ScriptedAlchemy** [comment]
Found the issue. Preparing a workaround

**Comment by ScriptedAlchemy** [comment]
@volkanunsal @loganfromlogan - can you try upgrading to `3.0.2-beta.3`

**Comment by luangjokaj** [comment]
@ScriptedAlchemy yep, now the warning is finally gone (webpack 4.18.0).

**Comment by ScriptedAlchemy** [comment]
@luangjokaj fantastic!

I just want to confirm its been resolved for @volkanunsal

**Comment by volkanunsal** [comment]
Yup,, working fine now. Thanks for the quick turnaround. 👍

**Comment by ScriptedAlchemy** [comment]
Awesome! Sorry for the screw up

**Comment by predssj4** [comment]
import { resolve } from 'dns' - this caused a problem in my case. Unncessary import.
