### ISSUE TITLE
Copy static methods to HOC

### ISSUE THREAD

**Issue by jepezi** [faceyspacey/react-universal-component#14]
I have a use-case where I need to call static methods in wrapped component on the server. Do you think we could (or if it's a good idea to) use `hoist-non-react-statics` to copy static methods to HOC like `react-redux` [does](https://github.com/reactjs/react-redux/blob/master/src/components/connectAdvanced.js#L281)?

**Comment by faceyspacey** [comment]
I don't know much about `hoist-non-react-statics`, but what methods do you want to copy, `preload`? It should work, give it a try.

**Comment by jepezi** [comment]
Sorry for being not clear. What I meant to say is this. Say I have my component `Gallery`. Now I use `universal`.

```js
const AsyncGallery = universal(() => import('./Gallery'), {
  resolve: () => require.resolveWeak('./Gallery')
})
```

And let's say I have static method in `Gallery`, now `AsyncGallery` doesn't have it. [hoist-non-react-statics](https://github.com/mridgway/hoist-non-react-statics) lets you copy static methods in `Gallery` onto `AsyncGallery` HOC.

However, I've tried to use it in my fork but there is a little problem on client when we're still waiting for async component to load. See my PR [here](https://github.com/mridgway/hoist-non-react-statics/pull/33) for details. In short, I think it's a good idea for HOC lib to consider this use case.

**Comment by faceyspacey** [comment]
It is a good use-case, but unless I'm mistaken, it would have to copy something from the yet to be imported module, so to do so, would require importing it when the app loads, which defeats the purpose. 

I guess we could tack static methods on `AsyncGallery` once the module loads, but that would lead to unpredictable usage. It's not a bad idea, but also we now support dynamic imports: 

```js
props => import(`./props.page`)
```

Which means the same `UniversalComponent` can be used for multiple components, so it wouldn't make much sense to start combining static methods on it, given collision potential, and simply given that it doesn't represent a 1-to-1 relationship between `UniversalComponent` to `ImportedComponent`.

I'm open to a PR if you feel strongly about this and have the best possible solutions for said challenges, but I'm going to close this for now.
