### ISSUE TITLE
HTML tags not working

### ISSUE THREAD

**Issue by futurfutur** [faceyspacey/react-universal-component#143]
```
//child component
import React from 'react'
export default () =>
  <div style={{marginLeft: 50}}>
    TEST
  </div>
```
```
// parent component
const UniversalComponent = universal(props => import(`./${props.page}`))

export default class App extends React.Component {

  render() {
    return (
      <div style={{color: 'pink'}}>
                <UniversalComponent page='Dull' />
      </div>
    )
  }
}
```

As a result 'TEST' word is pink but not margined. In browser console I have following error:

> warning.js:33 Warning: Prop `style` did not match. Server: "null" Client: "margin-left:50px"

In server console:

> > $ cross-env NODE_ENV=development node server/index.js
> Listening @ http://localhost:3000
> ‼ ｢wdm｣: Hash: ed8be47e37221066c334cecbc464f73c3f1893a7
> Version: webpack 4.16.5
> Child client:
>     Hash: ed8be47e37221066c334
>     Time: 3203ms
>     Built at: 2018-08-15 13:48:14
>        Asset       Size  Chunks             Chunk Names
>      Dull.js  798 bytes    Dull  [emitted]  Dull
>     main.css   44 bytes    main  [emitted]  main
>      main.js    795 KiB    main  [emitted]  main
>     Entrypoint main = main.css main.js
>     [./node_modules/babel-plugin-universal-import sync recursive] ./node_modules/babel-plugin-universal-import sync 160 bytes {main} [optional] [built]
>     [./node_modules/babel-plugin-universal-import/universalImport.js] 882 bytes {main} [built]
>     [./node_modules/fbjs/lib/shallowEqual.js] 1.58 KiB {main} [built]
>     [./node_modules/path-browserify/index.js] 6.04 KiB {main} [built]
>     [./node_modules/prop-types/checkPropTypes.js] 3.45 KiB {main} [built]
>     [./node_modules/react-dom/cjs/react-dom.development.js] 611 KiB {main} [built]
>     [./node_modules/react-dom/index.js] 1.33 KiB {main} [built]
>     [./node_modules/react-universal-component/dist/index.js] 13.2 KiB {main} [built]
>     [./node_modules/react/cjs/react.development.js] 48.3 KiB {main} [built]
>     [./node_modules/react/index.js] 190 bytes {main} [built]
>     [./src lazy recursive ^\.\/.*$] ./src lazy ^\.\/.*$ namespace object 160 bytes {main} [built]
>     [./src weak recursive ^\.\/.*$] ./src weak ^\.\/.*$ 256 bytes {main} [built]
>     [./src/App.css] 337 bytes {main} [built]
>     [./src/App.js] 3.28 KiB {main} [built]
>     [./src/index.js] 672 bytes {main} [built]
>         + 26 hidden modules
> 
>     WARNING in ./node_modules/babel-plugin-universal-import/universalImport.js 33:18-37
>     Critical dependency: the request of a dependency is an expression
>      @ ./src/App.js
>      @ ./src/index.js
> 
>     WARNING in ./node_modules/react-universal-component/dist/utils.js 59:11-29
>     Critical dependency: the request of a dependency is an expression
>      @ ./node_modules/react-universal-component/dist/index.js
>      @ ./src/App.js
>      @ ./src/index.js
>     Child extract-css-chunks-webpack-plugin node_modules/css-loader/index.js!src/App.css:
>         Entrypoint extract-css-chunks-webpack-plugin = *
>         [./node_modules/css-loader/index.js!./src/App.css] ./node_modules/css-loader!./src/App.css 206 bytes {extract-css-chunks-webpack-plugin} [built]
>         [./node_modules/css-loader/lib/css-base.js] 2.21 KiB {extract-css-chunks-webpack-plugin} [built]
> Child server:
>     Hash: cecbc464f73c3f1893a7
>     Time: 3329ms
>     Built at: 2018-08-15 13:48:14
>       Asset       Size  Chunks             Chunk Names
>        0.js   1.12 KiB       0  [emitted]
>        1.js    639 KiB       1  [emitted]
>     Dull.js  768 bytes    Dull  [emitted]  Dull
>     main.js    257 KiB    main  [emitted]  main
>     Entrypoint main = main.js
>     [./node_modules/babel-plugin-universal-import/universalImport.js] 882 bytes {main} [built]
>     [./node_modules/react-dom/server.js] 58 bytes {main} [built]
>     [./node_modules/react-universal-component/dist/index.js] 13.2 KiB {main} [built]
>     [./node_modules/react-universal-component/dist/report-chunks.js] 2.6 KiB {main} [built]
>     [./node_modules/react-universal-component/dist/requireUniversalModule.js] 5.38 KiB {main} [built]
>     [./node_modules/react-universal-component/server.js] 298 bytes {main} [built]
>     [./node_modules/react/cjs/react.development.js] 48.3 KiB {main} [built]
>     [./node_modules/react/index.js] 190 bytes {main} [built]
>     [./node_modules/webpack-flush-chunks/dist/flushChunks.js] (webpack)-flush-chunks/dist/flushChunks.js 7.11 KiB {main} [built]
>     [./server/render.js] 1.92 KiB {main} [built]
>     [./src lazy recursive ^\.\/.*$] ./src lazy ^\.\/.*$ namespace object 160 bytes {main} [built]
>     [./src weak recursive ^\.\/.*$] ./src weak ^\.\/.*$ 256 bytes {main} [built]
>     [./src/App.css] 0 bytes {main} [built]
>     [./src/App.js] 3.28 KiB {main} [built]
>     [path] external "path" 42 bytes {main} [built]
>         + 34 hidden modules
> 
>     WARNING in ./node_modules/babel-plugin-universal-import/universalImport.js 33:18-37
>     Critical dependency: the request of a dependency is an expression
>      @ ./src/App.js
>      @ ./server/render.js
> 
>     WARNING in ./node_modules/react-universal-component/dist/utils.js 59:11-29
>     Critical dependency: the request of a dependency is an expression
>      @ ./node_modules/react-universal-component/dist/index.js
>      @ ./src/App.js
>      @ ./server/render.js
> i ｢wdm｣: Compiled with warnings.

**Comment by ScriptedAlchemy** [comment]
Compare yours against the demo
