### ISSUE TITLE
React universal component breaks with a class based component

### ISSUE THREAD

**Issue by ElAnonimo** [faceyspacey/react-universal-component#144]
Both a functional component and its modification to a class based one are connected to the store.
A functional one renders ok but with the class based one this prints out to the console: https://pastebin.com/M0pCULPj
The full repo is on https://github.com/ElAnonimo/webpack4_2.
What does Article.js lack to properly render?

**Comment by ScriptedAlchemy** [comment]
doesnt look like its related to universal, ive never had any issue like this. Perhaps debug it further and report some initial disgnosis
