### ISSUE TITLE
HMR stuck in infinite loop

### ISSUE THREAD

**Issue by rtymchyk** [faceyspacey/react-universal-component#147]
I've noticed that HMR is broken for me because the universal HOC runs into an infinite loop on `componentWillReceiveProps`. Specifically removing this state update fixes it for me: https://github.com/faceyspacey/react-universal-component/blob/master/src/index.js#L196.

Unless I am missing something, what is there to guard against multiple hits to the lifecycle method with that state update (leading to an infinite re-render cycle)?

**Comment by ScriptedAlchemy** [comment]
would need to see a example to diagnose it, got a repo?

**Comment by lorenzomigliorero** [comment]
Same isse...

**Comment by ScriptedAlchemy** [comment]
Need a demo repo guys. Ill fix it but i cant replicate

**Comment by ScriptedAlchemy** [comment]
We are working on a. React 16 upgrade - there’s a PR open that’s fully functioning. We were able to replicate the issue there. 

If anyone can assist in debugging it - it will speed the process along ( we are working on it too)
