### ISSUE TITLE
server side rendering issue with universal component

### ISSUE THREAD

**Issue by scaledrop** [faceyspacey/react-universal-component#148]
It might be silly but with the following code config, it is not working if i import pages via props. When i try to load http://localhost:8080, Home page is not rendering from server but later on gets rendered from client properly. This is the [repository](https://github.com/scaledrop/react-ssr-boilerplate) I am referring to. You can check the code.

```
import React from "react";
import { Route } from "react-router-dom";
import universal from "react-universal-component";
import { Switch, Redirect } from "react-router";
import Nav from "../Components/Nav";
import "../assets/css/globals.css";
import { Helmet } from "react-helmet";
import Loading from "../Components/Loading";
import NotFound from "../Views/NotFound";

const UniversalComponent = universal(
  props => import(`../Views/${props.page}`),
  {
    loading: () => <Loading />
  }
);

export default () => (
  <div>
    <Helmet>
      <title>React SSR Boilerplate</title>
    </Helmet>
    <Nav />
    <Switch>
      <Route exact path="/">
        <UniversalComponent page="Home" />
      </Route>
      <Route exact path="/about">
        <UniversalComponent page="About" />
      </Route>
      <Route exact path="/article">
        <UniversalComponent page="Article" />
      </Route>
      <Route>
        <NotFound />
      </Route>
    </Switch>
  </div>
);
```

**Comment by scaledrop** [comment]
@faceyspacey All routes are working fine and async but not Home component. Can you please tell me why? Is there any way to fix it?

**Comment by scaledrop** [comment]
It is stateless and not connected to store as of now.

```
import React from 'react';
import { Helmet } from 'react-helmet';
import Content from '../../Components/Content';
import styles from './Home.css';

function Home() {
	return (
		<div>
			<Helmet encodeSpecialCharacters={true}>
				<title>React SSR Boilerplate • Home</title>
			</Helmet>
			<div className={styles.intro}>
				<h1 className={styles.title}>React Boilerplate</h1>
				<p className={styles.desc}>A minimal React boilerplate with Server side rendering.</p>
			</div>
		</div>
	);
}

export default Home;
```

**Comment by scaledrop** [comment]
@faceyspacey I need you interruption here. Please help me get out of this.

**Comment by scaledrop** [comment]
@kyle-johnson Hey, It works like a charm. Thanks! The issue was with Babel plugin only. But do you have any idea to eliminate this dependency completely? either by updating the Babel or universal-component. I am not willing to import this plugin every time on the top of the serverjs.

**Comment by scaledrop** [comment]
@kyle-johnson on production this patch is not working.

**Comment by iiroj** [comment]
For what it's worth, I'm also facing a similar issue. I've created an SSR boilerplate with the "universal family" and it's working great. I thought about simplifying by switching to [connected-react-router](https://github.com/supasate/connected-react-router), but with that I'm getting this issue.

In development mode, SSR works fine (enabled via env variable), but after building and running in production mode the pages are only rendered with "Loading..." (and emotion styles).

You can see the colde here:
https://github.com/iiroj/react-universal-boilerplate/blob/connected-react-router/src/server/utils/render.jsx

The boilerplate is basically a babeled server and a client bundle built with webpack. Again, the master branch works fine, but that uses [redux-first-router](https://github.com/faceyspacey/redux-first-router).

**Comment by kyle-johnson** [comment]
I moved to defining my universals all in one file (components/universals.js) and sticking the babel call at the top like so:

```javascript
import { setHasBabelPlugin } from "react-universal-component";
setHasBabelPlugin();

const Home = universal(import("components/pages/Home"));
const About = universal(import("components/pages/About"));
const Login = universal(import("components/pages/Login"));
const Inbox = universal(import("components/pages/Inbox"));
const Compose = universal(import("components/pages/Compose"));
const People = universal(import("components/pages/People"));
```

That's working server-side and works in production (dev gets the fully rendered component from the server, re-renders first with "Loading...", then re-renders again with the actual component).

**Comment by scaledrop** [comment]
@kyle-johnson Yes It makes sense to create a sample repo that explains it well. Also please make sure the routes come dynamically from external files. We can't import all the components one by one in the same file. We'll just loop through them and they will be imported. Waiting for your repo to be shared.

**Comment by ScriptedAlchemy** [comment]
hey guys, one issue is i see is you have the import in the same file as everything else

You need to put the RUC utility file outside the folder thats going to import

If you look at the universal demo https://github.com/faceyspacey/universal-demo/tree/master/src

You will see i have a file called UniversalComponent. which is outside the `import()` context

What happens is the chunk names seem to get confused and the last chunk gets the incorrect name. Its like universal swollows its self. I am not sure hot to resolve it, all i know is its related to the babel plugin

**Comment by ScriptedAlchemy** [comment]
If anyone knows how to fix it. Im all ears!! 

But all you need to do is create a ruc utility file and put it outside the folder context you plan to dynamically import.

then, what i do is use `import()` as a prop. Then i am able to use RUC anywhere i require it, multiple levels down

**Comment by iiroj** [comment]
Thanks, @ScriptedAlchemy. If I move my `UniversalComponent` somewhere else and change it to accept the whole `() => import('../pages/MyPage')` as a prop, it sort of starts working.

When I hardcode routes like so, everything works:
``` javascript
<Switch>
  <Route render={() => <UniversalComponent src={() => import('../pages/NotFound')} />} />
</Switch>
```

This results with a server-side rendered 404 page.

However, if I define my routes in an array and map it in the render, I start getting erros from [webpack-flush-chunks](https://github.com/faceyspacey/webpack-flush-chunks): `[FLUSH CHUNKS]: Unable to find pages-NotFound in Webpack chunks. Please check usage of Babel plugin.`.

This results in SSR working properly, but some bundles missing and thus a flashing _Loading..._ when React mounts client-side.

```javascript
const routes = [{
  page: 'NotFound'
}];

...

<Switch>
  {routes.map((route, key) => (
      <Route
        key={key}
        exact={route.exact}
        path={route.path}
        render={() => <UniversalComponent src={() => import(`../pages/${route.page}`)} />}
      />
    ))}
</Switch>
```

The babeled output is probably what's different:

For the hard-coded version the id receives the full Component path:

```javascript
_react.default.createElement(_reactRouterDom.Route, {
  render: () => _react.default.createElement(_UniversalComponent.default, {
    src: () => (0, _universalImport3.default)({
      id: "../pages/NotFound",
      file: "/REDACTED/src/client/components/App.jsx",
      path: () => _path3.default.join(__dirname, '../pages/NotFound'),
      resolve: () => require.resolveWeak('../pages/NotFound'),
      chunkName: () => "pages-NotFound"
    })
  })
});
```

For the mapped version, however, it does not:

```javascript
_react.default.createElement(_reactRouterDom.Switch, null, routes.map((route, key) => _react.default.createElement(_reactRouterDom.Route, {
  key: key,
  exact: route.exact,
  path: route.path,
  render: () => _react.default.createElement(_UniversalComponent.default, {
    src: (0, _universalImport2.default)({
      id: "../pages/",
      file: "/REDACTED/src/client/components/App.jsx",
      path: () => _path2.default.join(__dirname, `../pages/${route.page}`),
      resolve: () => require.resolveWeak(`../pages/${route.page}`),
      chunkName: () => `pages/${route.page}`
    })
  })
})));
```

I'm just guessing here.

**Comment by ScriptedAlchemy** [comment]
Fixes are being worked on for chunk mismatch’s. 

This library family has grown significantly in popularity- as such I needed to look at an update to try and normalize the chunk resolution

**Comment by GuillaumeCisco** [comment]
I have the exact same problem as @iiroj  since I updated `react-universal-component` from `2.9.0` to `3.0.0` (still seeing it in 3.0.3).
Using a map version will produce a `/` and not a `-`. Simply testing with a hard-coded version make it works.

The error is `[FLUSH CHUNKS]: Unable to find routes-challenge-preload-index in Webpack chunks. Please check usage of Babel plugin.`

Do you think it is a `babel-plugin-universal-import` or `react-universal-component` issue?

**Comment by ScriptedAlchemy** [comment]
I’m sorry if I didn’t specify that before. I thought I had! 

If there’s insufficient docs around this, do any of you want to open a PR?

**Comment by ScriptedAlchemy** [comment]
I’m hoping that there is enough flexibility to meet everyone’s need!

**Comment by GuillaumeCisco** [comment]
I'm linking the issue from webpack-flush-chunks:
https://github.com/faceyspacey/webpack-flush-chunks/issues/74
