### ISSUE TITLE
Allow custom isHMR fn

### ISSUE THREAD

**Issue by MMMalik** [faceyspacey/react-universal-component#153]
Hey,

I've been testing react-universal-component and I've encountered some problems with HMR , particularly with [this line](https://github.com/faceyspacey/react-universal-component/blob/master/src/index.js#L30).

It turns out that `module.hot.data` is initially `undefined` but after first HMR update, it's always an object. As a result, the built-in `isHMR()` returns always a truthy value after first HMR update.
This causes weird toggling effects on every render of 'universal' component, even long after its module has been updated.

I understand if you are unwilling to change your built-in way of handling HMR, but have you considered a possibility of adding a `isHMR` option? Then we could pass something like:
```
{ isHMR: () => module.hot && module.hot.status() === 'apply' }
```
This seems to be working in my case but I wonder if it might be helpful for others as well.

PS. I can provide a pull request if you wish.

**Comment by MMMalik** [comment]
Okay, so it looks like changing current isHMR to `module.hot && module.hot.status() === 'apply'` simply disables universal component's HMR handling at all. However, the culprit seems to be the line indicated in [this issue](https://github.com/faceyspacey/react-universal-component/issues/147).
So, I've tried the latest [changes](b7ee921722ef026ca94e42bb885395029bed0dd4) in [react16 branch](https://github.com/faceyspacey/react-universal-component/tree/react16) and things appear to be working fine in my project. Any chances these changes make into release anytime soon?

**Comment by ScriptedAlchemy** [comment]
It’s a WIP, still need to update a few tests and there’s another release in front of it :P 

One release is new and improved chunk resolution. The other is R16. Both considered breaking changes

**Comment by ScriptedAlchemy** [comment]
okay if u wanna PR this you can,
