### ISSUE TITLE
How to retry to load a failed chunk?

### ISSUE THREAD

**Issue by mycolaos** [faceyspacey/react-universal-component#154]
A chunk can fail to load because of poor connection. How to retry to load it? I don't see any API for that.

P.S.: Not using "babel-plugin-universal-import".

**Comment by ScriptedAlchemy** [comment]
Ohhhh this is a good one! 

I’ve wanted this for a while. Here’s one really basic solution... use the error prop and pass universal another universal component instead of an error component. So when it fails, it just shows it’s self, therefore causing another request to attempt.

**Comment by mycolaos** [comment]
My solution is to recreate `UniversalComponent` inside the HOC which creates it.

@ScriptedAlchemy i'm afraid your solution can cause a infinite recursion. Just imagine you're offline...

**Comment by emphaticsunshine** [comment]
What if it has to be manually retried again. I have an async component which is downloaded on click. I am handling timeout by displaying error to user saying that try again. Now if user trys again, it's not even going to try to download the component and just error out.

**Comment by ScriptedAlchemy** [comment]
I’d like to handle this, but this feature is low on the priority list right now. 

I assume we need a timeout on the async require function, along with ability to reload it. 

You could also use the preload function in universal. And manually execute that somewhere which should tell webpack to re require the code.

**Comment by mycolaos** [comment]
@ScriptedAlchemy  the `preload` function does not seem to work for this purpose. 
It triggers an error when try to preload after a first failed attempt:
`Uncaught (in promise) Error: Loading chunk 48 failed.`
