### ISSUE TITLE
Super long build time / freeze with many files in directory

### ISSUE THREAD

**Issue by owczar1981** [faceyspacey/react-universal-component#157]
This solution worked for me well until my project got significantly bigger. I have a project structure that looks like this:
````
...
- routes
    - RouteA
        - RouteA.js
    - RouteB
        - RouteB.js
    (... about 64 more routes)
    - index.js
    - UniversalComponent.js
...
````

`index.js` contains a ReactRouter Switch with all of the routes dynamically imported by `UniversalComponent` contained in the same folder.

After launching a build in development or production mode - the build can't be finished or maybe it is lasting longer than 30 minutes. When I remove `UniversalComponent.js` from the directory or leave only 2 or 3 routes inside the folder, it passes without problems.

Do you have any idea what's going wrong or could you point me in some direction? I'm stuck with this for a full day now. I had this problem already about 3 months earlier but I left it for later, as I didn't need SSR earlier.

I'm using the **latest** versions of all of my dependencies - react, webpack, babel etc.

I'm also using Hot Loader.

My webpack development config:

````js
var path = require('path');
var webpack = require('webpack');
var HtmlWebpackPlugin = require('html-webpack-plugin');
var HardSourceWebpackPlugin = require('hard-source-webpack-plugin');

var config = require('./../config');

module.exports = {
    name: 'client',
    devtool: 'cheap-eval-source-map',
    target: 'web',
    mode: 'development',
    entry: {
        app: [path.join(config.srcDir, 'index.js')]
    },
    output: {
        filename: '[name].bundle.js',
        chunkFilename: '[name].chunk.js',
        path: config.distDir,
        publicPath: '/'
    },
    resolve: {
        modules: [
            'node_modules',
            config.srcDir
        ]
    },
    plugins: [
        new HardSourceWebpackPlugin(),
        new HtmlWebpackPlugin({
            template: config.srcHtmlLayout,
            inject: false,
            chunksSortMode: 'none'
        }),
        new webpack.DefinePlugin({
            'process.env.NODE_ENV': JSON.stringify('development')
        }),
        new webpack.NamedModulesPlugin(),
        new webpack.HotModuleReplacementPlugin()
    ],
    module: {
        rules: [
            {
                test: /\.js$/,
                exclude: /node_modules/,
                use: 'babel-loader'
            },
            // Modular Styles
            {
                test: /\.css$/,
                use: [
                    { loader: 'style-loader' },
                    { 
                        loader: 'css-loader',
                        options: {
                            modules: true,
                            importLoaders: 1,
                            localIdentName: '[name]_[local]_[hash:base64:5]'
                        }
                    },
                    { loader: 'postcss-loader' }
                ],
                exclude: [path.resolve(config.srcDir, 'styles')],
                include: [config.srcDir]
            },
            {
                test: /\.scss$/,
                use: [
                    { loader: 'style-loader' },
                    {
                        loader: 'css-loader',
                        options: {
                            modules: true,
                            importLoaders: 1,
                            localIdentName: '[name]_[local]_[hash:base64:5]'
                        }
                    },
                    { loader: 'postcss-loader' },
                    {
                        loader: 'sass-loader',
                        options: {
                            includePaths: config.scssIncludes
                        }
                    }
                ],
                exclude: [path.resolve(config.srcDir, 'styles')],
                include: [config.srcDir]
            },
            // Global Styles
            {
                test: /\.css$/,
                use: ['style-loader', 'css-loader', 'postcss-loader'],
                include: [path.resolve(config.srcDir, 'styles')]
            },
            {
                test: /\.scss$/,
                use: [
                    'style-loader',
                    'css-loader',
                    'postcss-loader',
                    {
                        loader: 'sass-loader',
                        options: {
                            includePaths: config.scssIncludes
                        }
                    }
                ],
                include: [path.resolve(config.srcDir, 'styles')]
            },
            // Fonts
            {
                test: /\.(ttf|eot|woff|woff2)$/,
                loader: "file-loader",
                options: {
                    name: "fonts/[name].[ext]",
                }
            },
            // Files
            {
                test: /\.(jpg|jpeg|png|gif|svg)$/,
                loader: "file-loader",
                options: {
                    name: "static/[name].[ext]",
                }
            }
        ]
    },
    devServer: {
        hot: true,
        contentBase: config.serveDir,
        compress: true,
        historyApiFallback: {
            index: '/'
        },
        host: '0.0.0.0',
        port: 4000
    }
}
````

**Comment by owczar1981** [comment]
In addition, I have inspected the build with devtools and here are the top entries of the profile result. Maybe this will give some additional clues:

![Profile Dump](https://content.screencast.com/users/unskilled/folders/Jing/media/f28bd7fd-8715-4aca-a15d-2041b0ddb8ed/2018-09-18_1449.png)

**Comment by ScriptedAlchemy** [comment]
This is related to webpack. You need to lighten your build for dev mode. Reduce transformation as much as possible. 

Investigate ways to optimize webpack. The root cause is usually limit chunks plugin. For this, you have to optimize the build configuration. 

I’m currently facing the same issue and am in the process of overhauling the build performance. Brings dramatic improvements

**Comment by owczar1981** [comment]
I tried a lot of stuff, though not limiting chunks as i recall.

If you are at the same stage as I am, I would be greatfull for some bullet points which optimizations helped in your case :)

**Comment by pho3nixf1re** [comment]
I dropped in [HardSourceWebpackPlugin](https://github.com/mzgoddard/hard-source-webpack-plugin) which helped drastically. Dev re-builds went from 60+ seconds to an average of 10 seconds. Although it uses a massive amount of local disk space (~300mb) :) .

**Comment by owczar1981** [comment]
Unfortunarely, this is the plugin I thought would help me with the problem, but it didn't change anything :(

**Comment by ScriptedAlchemy** [comment]
HardSource did the trick for me, first build is a little slow but they speed up. 

I would suggest digging deeper into your webpack builds performance in dev mode. 

the SSR build is what takes the longest, maxChunksPlugin is very slow - its a wide spread issue across the webpack community who use it

**Comment by pho3nixf1re** [comment]
I have to revise my previous statement some. HardSource really helps but that wasn't actually what my problem was. I'm stating this here in case someone else happens by.

So I used the callback for the `universal` factory which used a prop value to create a dynamic chunk. Example:

```js
universal(({ component }) => import(`app/components/${component}`))
```

The problem is that each of my components contains css and other helpers loosely based off a 'feature first' component organization. The problem is that webpack will create a chunk for all possibilities of that path, not just for the components that I explicitly wanted to split on. This and the fact that I had a couple universal components in the path caused the build to explode in complexity. Once I changed over to explicitly export each component things went... much much better. The different has been a couple orders of magnitude better. So extreme that all of my optimizations became moot. I'll be keeping HardSource around for convenience but that was not the fix in my case.

**Comment by ScriptedAlchemy** [comment]
Just to follow up here, i now support multiple webpack comments. 

While you are right, import() will cause it to consume anything in its path. You can use magic comments to ignore some aspects. 

one trick i use is `import('/containers/${page}.js')` which isolates the consumption to just JS files. 

Ive also used things like ignore loader and babel cacheing :)
