### ISSUE TITLE
How to keep track of reducers that had been loaded?

### ISSUE THREAD

**Issue by futurfutur** [faceyspacey/react-universal-component#159]
In doc you don't specify where you get **otherReducers** parameter. What's the best way to get all the reducers that has been already loaded?
```
onLoad: (module, info, props, context) => {
  context.store.replaceReducer({ ...otherReducers, foo: module.fooReducer })
}
```

So far I've came up with following solution:

```
let reducers = {};

const UniversalComponent = universal(props => import(`./modules/${props.componentName}`), {
    
    onLoad(module, info, props, context) {
      if (module.reducers) {
        reducers = { ...reducers, ...module.reducers };
        context.store.injectReducers(reducers); 
      }
    }
  })
```

**Comment by ScriptedAlchemy** [comment]
that would work, i dont really have a good solution for things like this currently - however i dont see anything wrong with just storing it in an object

This is one of the aims of our Rudy Router project, It provides a full async Route controller with at ability to hack on middleware and reducers
