### ISSUE TITLE
v3.0.3 on npm?

### ISSUE THREAD

**Issue by wmertens** [faceyspacey/react-universal-component#160]
I noticed that npm is v3.0.3 but on github it's still 3.0.0?

**Comment by ScriptedAlchemy** [comment]
all my CI stiff broke, do you really need it via GH? if so ill need to mission semantic release into this thing and config it at some point

**Comment by wmertens** [comment]
Well it's just surprising that the code on github is 3.0.0, makes me wonder what's the diff with 3.0.3…

**Comment by ScriptedAlchemy** [comment]
Dude ur totally right and it’s cause I’ve been doing it manually. Gimme some time to set up semevr again. 

Like I’m in the wrong. But I’m just trying to unblock u quick

**Comment by ScriptedAlchemy** [comment]
I know. It’s killing me.  I updated semver and the tokens are under faceyspacey. So I can’t add with tokens and automate it all again. 

I’m gonna talk about elevated permissions. CI across so many projects are down and I’m manually releasing and versioning. 

It’s hell. Thanks for your patience and I I want automation just as bad

**Comment by ScriptedAlchemy** [comment]
Closing this as I’m fixing automated releases across everything
