### ISSUE TITLE
Labeling snippets in the Readme

### ISSUE THREAD

**Issue by kaigouthro** [faceyspacey/react-universal-component#168]
might be nice to have little titles on which snippets go where, and that you bundled some snips together when it looks to be three different options

a little "index.js" or "app.js" or "container/index.js" label ahead or below the code examples would go a  long way in speeding things up for those of us ambitious types who are still only a couple months into java, but want the best.

**Comment by ScriptedAlchemy** [comment]
Fair point. We do provide a demo project though.  Lol

I know the docs need work though. Right now lots of time is going into Rudy and redux first router

React merged RUC a few months back,so I’m hesitant to invest loads of time in stuff like that at this point
