### ISSUE TITLE
Upgrade to 3.0.3 I get FOUC

### ISSUE THREAD

**Issue by primozs** [faceyspacey/react-universal-component#169]
When I upgrade from 
"react-universal-component": "^2.9.0",
to
"react-universal-component": "^3.0.3"
I start to get flash of unstyled content. When I downgrade it back below 3.* it works fine again.

Other packages that I use:
"webpack-flush-chunks": "^2.0.3",
"babel-plugin-universal-import": "^3.1.2",
"extract-css-chunks-webpack-plugin": "^3.2.1",

What could be the reason for this?
Cheers

**Comment by ScriptedAlchemy** [comment]
Check the documentation around ignore Babel rename which can be added to RUC. 

Css however is now standalone and in no way depends on universal. Are you on Webpack 4?

Console log out what’s coming from flush chunks.

**Comment by primozs** [comment]
This is funny, today I was upgrading packages and I tried several times to upgrade react-universal-component without success. Finally now that I wanted to record how it looks together with logs and config it started to work. Strange. Thank you any way! I will reopen if it starts failing.
Cheers!
