### ISSUE TITLE
React Router Switch Support

### ISSUE THREAD

**Issue by dawidvdh** [faceyspacey/react-universal-component#17]
Hey love this whole set up you have created, I am just stuck with one thing though and thats using react router, My set up is heavily inspired by [flush-chunks-boilerplate-webpack-chunknames](https://github.com/faceyspacey/flush-chunks-boilerplate-webpack-chunknames) almost exactly the same, however when i make use of react router and i receive a failed checksum from server to client markup:

```
 (client) bout!</a></nav><div data-reactid="6">Loa
 (server) bout!</a></nav><div id="home" data-react
```
It seems that the server renders it just fine but then the client reloads it? I havent done a very deep dive yet but was wondering if there were known issues with react router?

I use react-router in the following way:

The main App:

```javascript
const Home = universal(() => import('./Home'), {
  resolve: () => require.resolveWeak('./Home'),
  chunkName: 'Home'
})

const App = () => (
  <div>
    <Helmet {...config.head} />
    <Menu />
    <Switch>
      <Route path="/" component={Home} exact />
      <Route path="/about" component={About} exact />
      <Route component={NotFound} exact />
    </Switch>
  </div>
)
```

Client:

```javascript
render(
    <AppContainer>
      <Provider store={store} key="provider">
        <BrowserRouter forceRefresh={!supportsHistory}>
          <App />
        </BrowserRouter>
      </Provider>
    </AppContainer>,
    document.getElementById('root')
  )
```

Server:

```javascript
const component = (
    <Provider store={store} key="provider">
      <StaticRouter
        location={req.url}
        context={reactRouterContext}
      >
        <App />
      </StaticRouter>
    </Provider>
  )
```

Any Help would be Greatly Appreciated.

**Comment by faceyspacey** [comment]
Glad you're digging it. Have you checked to make sure the chunk corresponding to `Home` is being embedded in the page. It seems you need to do this:

```js
universal(() => import(/* webpackChunkName: 'Home' */, './Home')
```

If you're using [babel-plugin-dual-import](https://github.com/faceyspacey/babel-plugin-dual-import), it should do it for you. Check the transpiled output and make sure you see `Promise.all` etc, which is what the dual-import plugin adds.

The challenge with my setup is that it is the "frameworkless" approach to what Next.js does, which means you gotta get all the webpack config right. It's kinda unavoidable. Soon I'll be consolidating all my stuff and making it even easier, but you'll still have to make sure the webpack config is right. 

Can you paste your webpack config, your babelrc, and the transpiled output of your call to `universal/import()`.

PS. have you checked out: https://github.com/faceyspacey/redux-first-router yet. React Router should work but Redux-First Router is the future of Redux routing :)

**Comment by dawidvdh** [comment]
Hey yes i am using  (babel-plugin-dual-import)[https://github.com/faceyspacey/babel-plugin-dual-import],

here is may `.babelrc`:

```json
{
  "presets": [
    [
      "env",
      {
        "modules": false
      }
    ],
    "es2015",
    "react",
    "stage-2"
  ],
  "plugins": [
    "dual-import",
    "transform-decorators-legacy"
  ],
  "env": {
    "production": {
      "only": [
        "src"
      ],
      "plugins": [
        "transform-react-remove-prop-types",
        "transform-react-constant-elements",
        "transform-react-inline-elements"
      ]
    },
    "development": {
      "plugins": ["react-hot-loader/babel"]
    }
  }
}
```

my webpack dev server config:

```javascript
const fs = require('fs')
const path = require('path')
const webpack = require('webpack')
const WriteFilePlugin = require('write-file-webpack-plugin')
const Dotenv = require('dotenv-webpack')
const autoprefixer = require('autoprefixer')

const res = p => path.resolve(__dirname, p)

const modeModules = res('../node_modules')
const entry = res('../src/server/render.js')
const output = res('../buildServer')

// if you're specifying externals to leave unbundled, you need to tell Webpack
// to still bundle `react-universal-component`, `webpack-flush-chunks` and
// `require-universal-module` so that they know they are running
// within Webpack and can properly make connections to client modules:
const externals = fs
  .readdirSync(modeModules)
  .filter(
  x =>
    !/\.bin|react-universal-component|require-universal-module|webpack-flush-chunks/.test(
      x
    )
  )
  .reduce((externals, mod) => {
    externals[mod] = `commonjs ${mod}`
    return externals
  }, {})

module.exports = {
  name: 'server',
  target: 'node',
  // devtool: 'source-map',
  devtool: 'eval',
  entry: [entry],
  externals,
  output: {
    path: output,
    filename: '[name].js',
    libraryTarget: 'commonjs2',
    publicPath: '/static/'
  },
  module: {
    rules: [
      {
        test: /\.jsx?$/,
        exclude: /node_modules/,
        use: 'babel-loader'
      },
      {
        test: /\.scss$/,
        exclude: /node_modules/,
        use: [{
          loader: 'css-loader/locals',
          options: {
            modules: true,
            localIdentName: '[name]__[local]--[hash:base64:5]'
          }
        },
          'sass-loader',
        {
          loader: 'postcss-loader',
          options: {
            plugins: () => [
              autoprefixer({ browsers: 'last 2 versions' })
            ]
          }
        }]
      }, {
        test: /\.(jpg|png|gif|svg|ico)$/,
        use: [{
          loader: 'url-loader'
        }]
      }
    ]
  },
  resolve: {
    extensions: ['.json', '.js', '.jsx'],
    alias: {
      api: path.resolve(__dirname, 'src/api/'),
      components: path.resolve(__dirname, 'src/components/'),
      reducers: path.resolve(__dirname, 'src/redux/reducers/')
    }
  },
  plugins: [
    new WriteFilePlugin(),
    new webpack.optimize.LimitChunkCountPlugin({
      maxChunks: 1
    }),
    new webpack.ProvidePlugin({
      fetch: 'isomorphic-fetch'
    }),
    new Dotenv({
      path: path.resolve(__dirname, '../.env'),
      safe: false
    }),
    new webpack.DefinePlugin({
      'process.env.SERVER': JSON.stringify(true),
      'process.env.NODE_ENV': JSON.stringify('development')
    })
  ]
}

```

my webpack client dev config:

```javascript
const path = require('path')
const webpack = require('webpack')
const WriteFilePlugin = require('write-file-webpack-plugin') // here so you can see what chunks are built
const ExtractCssChunks = require('extract-css-chunks-webpack-plugin')
const Dotenv = require('dotenv-webpack')
const autoprefixer = require('autoprefixer')
const ServiceWorkerPlugin = require('serviceworker-webpack-plugin')

module.exports = {
  name: 'client',
  target: 'web',
  // devtool: 'source-map',
  devtool: 'eval',
  entry: [
    'webpack-hot-middleware/client?path=/__webpack_hmr&timeout=20000&reload=false&quiet=false&noInfo=false',
    'react-hot-loader/patch',
    path.resolve(__dirname, '../src/client.js')
  ],
  output: {
    filename: '[name].js',
    chunkFilename: '[name].js',
    path: path.resolve(__dirname, '../buildClient'),
    publicPath: '/static/'
  },
  module: {
    rules: [
      {
        test: /\.jsx?$/,
        exclude: /node_modules/,
        use: 'babel-loader'
      },
      {
        test: /\.scss$/,
        use: ExtractCssChunks.extract({
          use: [{
            loader: 'css-loader',
            query: {
              modules: true,
              localIdentName: '[name]__[local]--[hash:base64:5]'
            }
          },
            'sass-loader',
          {
            loader: 'postcss-loader',
            options: {
              plugins: () => [
                autoprefixer({ browsers: 'last 2 versions' })
              ]
            }
          }]
        })
      },
      {
        test: /\.(jpg|png|gif|svg|ico)$/,
        use: [{
          loader: 'url-loader'
        }]
      }
    ]
  },
  resolve: {
    extensions: ['.json', '.js', '.jsx'],
    alias: {
      api: path.resolve(__dirname, 'src/api/'),
      components: path.resolve(__dirname, 'src/components/'),
      reducers: path.resolve(__dirname, 'src/redux/reducers/')
    }
  },
  plugins: [
    new WriteFilePlugin(),
    new ExtractCssChunks(),
    new webpack.optimize.CommonsChunkPlugin({
      names: ['bootstrap'], // needed to put webpack bootstrap code before chunks
      filename: '[name].js',
      minChunks: Infinity
    }),
    new webpack.HotModuleReplacementPlugin(),
    new webpack.NoEmitOnErrorsPlugin(),
    new webpack.DefinePlugin({
      'process.env': {
        NODE_ENV: JSON.stringify('development')
      }
    }),
    new webpack.ProvidePlugin({
      fetch: 'isomorphic-fetch'
    }),
    new Dotenv({
      path: path.resolve(__dirname, '..', '.env'),
      safe: false
    }),
    new ServiceWorkerPlugin({
      entry: path.join(__dirname, '..', 'src/sw.js'),
      excludes: ['*hot-update*']
    })
  ]
}
```
and then finally the transpiled output:

```javascript
= (0, _reactUniversalComponent2.default)(function () {
  return Promise.all([__webpack_require__.e/* import() */(1).then(__webpack_require__.bind(null, 263)), (0, _importCss3.default)('Home')]).then(function (proms) {
    return proms[0];
  });
}, {
  resolve: function resolve() {
    return /*require.resolve*/(263);
  },
  chunkName: 'Home'
});
```

**Comment by dawidvdh** [comment]
Honestly though i prefer your frameworkless structure, and yes i have seen your router about and I will check it out in future.

**Comment by faceyspacey** [comment]
yea, that's the whole point. The next.js framework approach is not the correct approach for power users.

...the transpiled output is correct, and your webpack config looks solid. what about the chunks and stylesheets embedded in the page. do you see the Home chunk there?

Also log the result of `flushChunkNames()`. Do you see `Home`? 

Next, log the `scripts` and `stylesheets` returned from `webpack-flush-chunks`. Do you see them there?

**Comment by dawidvdh** [comment]
Okay so the code snippet i used to logout:

```javascript
 const chunkNames = flushChunkNames()
  console.log('Chunk Names ', chunkNames)
  const { scripts, stylesheets, cssHashRaw, publicPath } = flushChunks(clientStats, { chunkNames })
  console.log('Webpack Flush Chunks: scripts', scripts)
  console.log('Webpack Flush Chunks: scripts', stylesheets)
```

What was returned in the terminal
```
Chunk Names  [ 'NotFound' ]
Webpack Flush Chunks: scripts [ 'bootstrap.js', 'NotFound.js', 'main.js' ]
Webpack Flush Chunks: scripts [ 'main.css' ]
Chunk Names  [ 'Home' ]
Webpack Flush Chunks: scripts [ 'bootstrap.js', 'Home.js', 'main.js' ]
Webpack Flush Chunks: scripts [ 'main.css' ]
Chunk Names  [ 'NotFound' ]
Webpack Flush Chunks: scripts [ 'bootstrap.js', 'NotFound.js', 'main.js' ]
Webpack Flush Chunks: scripts [ 'main.css' ]
```
and then also in the browser console i have the following warning: `[DUAL-IMPORT] no chunk,  Home , found in "window.__CSS_CHUNKS__"`.

and then finally the inlined css chunks looks like this:

```javascript
window.__CSS_CHUNKS__={"About":"\u002Fstatic\u002FAbout.css","main":"\u002Fstatic\u002Fmain.css"};
```

**Comment by faceyspacey** [comment]
And is `HOME` appearing in your served HTML, and does it have the code when you click it?

Also, what's `NotFound`? That looks like your use of `universal` uses `NotFound` as the `error` option as in the boilerplate. 

Also, does `Home` have any CSS? Only `About` seems to generate a css file. 

...i dont suppose i can just get access to the repo??

**Comment by dawidvdh** [comment]
haha yeah i think you just need to actually see the repo, I will create a sample version of it as this is a private repo then post back here with a link probably in the next day.

Also to answer the other question:

1. Yes home does appear and it does have code when i click it.
2. `NotFound` is like a 404 component when none of the routes match `<Route component={NotFound} exact />` (see app.js posted in the first comment)
3. Home does not have any CSS only About does.

thank you for all your help so far!

**Comment by faceyspacey** [comment]
we're gonna get this. ..sounds like ur using `universal` correctly otherwise. I myself am curious as to what your issue is since `Home` is getting embedded. 

Question: is there a spinner/loading component in place of where `Home` is supposed to be? The mismatch would occur--or at least my hypothesis for your particular situation--when the chunk is not in fact embedded on the page, and the client has to retrieve it again. In which case, the checksums won't match because the server rendered Home, but the client renders the loading component (while downloading the Home chunk).

Check your network requests. Is a subsequent request made for the Home chunk? I know it's embedded correctly in the page, but perhaps Webpack isn't aware of it.

By the way, there are a great number of reasons why checksums might not match. For example, if you have `if (typeof window !== undefined)` the client will display something different than what's rendered. 

So everything could in fact be working (and it seems it really should be), but you get a checksum mismatch because your code does something different on the server than the client. In which case, checking network requests would not show the downloading of your chunk (since you did it correctly).

So does the network tab of chrome devtools make a second request to download the chunk after page load?

**Comment by dawidvdh** [comment]
Yes that is correct, the client is retrieving it again... so the server renders it out correctly then the client renders out `loading...` and fetches the home script again. 

And yes I am painfully aware of the numerous ways to get mismatches and i can promise you its not due to other code.

**Comment by faceyspacey** [comment]
...i think i might know the problem now: do you render your "dynamic chunks" before `main.js`?

if main is evaluated before the dynamic chunks, they wont be there on first render, and loading... will show.

webpack-flush-chunks handles this all for you, but perhaps you're taking a more manual route.

**Comment by faceyspacey** [comment]
one other thing to try at this juncture: *dont use react-router* and prove your initial hypothesis that it could be something wrong with react-router. perhaps passing it as the component prop to <Route /> is a problem.

**Comment by faceyspacey** [comment]
u dont need to remove react-router from ur app, just dont wrap tyour universal component in a route. ...if that still doesn't work, try using your current setup, temporarily delete the react router providers, etc, and make your app do nothing but render the universal Home component. 

in short, reduce ur application code to the smallest thing possible.

**Comment by dawidvdh** [comment]
Okay so i have modified `App.js` from this:

```javascript
const App = () => (
  <div>
    <Helmet {...config.head} />
    <Menu />
    <Switch>
      <Route path="/" component={Home} exact />
      <Route path="/about" component={About} />
      <Route component={NotFound} />
    </Switch>
  </div>
)
```

to this:

```javascript
const App = () => (
  <div>
    <Helmet {...config.head} />
    <Menu />
    <Home />
  </div>
)
```

and there are no longer any render mismatches...

**Comment by faceyspacey** [comment]
sick. progress.

**Comment by dawidvdh** [comment]
Must be passing it as a prop thats causing the issue then?

**Comment by faceyspacey** [comment]
try using `<Route render={`

**Comment by faceyspacey** [comment]
also do only `Home`. do one at a time. keep `<Menu />` the plain way.

**Comment by faceyspacey** [comment]
also try with and without `<Switch />`. we need to determine if the problem is:

- component={
- <Route /> as a whole
- <Switch />

Then if one of these work, we can figure out the characteristics of the one that breaks it.

**Comment by dawidvdh** [comment]
cool went to this:

```javascript
const App = () => (
  <div>
    <Helmet {...config.head} />
    <Menu />
    <Switch>
      <Route path="/" render={props => (<Home {...props} />)} exact />
    </Switch>
  </div>
)
```

and now there is a render mismatch again...

**Comment by faceyspacey** [comment]
try without the Switch now :)

**Comment by faceyspacey** [comment]
and if without the Switch works, try with `component={` again. Then we know it was the switch. ...crossing fingers.

**Comment by dawidvdh** [comment]
Same issue with out switch hey:

```javascript
const App = () => (
  <div>
    <Helmet {...config.head} />
    <Menu />
    <Route path="/" render={props => (<Home {...props} />)} exact />
  </div>
)
```

**Comment by faceyspacey** [comment]
...next stage:

- open node_modules/react-universal-component, and log the props within `render` to see why it thinks it doesnt have the component.

**Comment by faceyspacey** [comment]
first actually, try this:

```js
const App = () => (
  <div>
    <Helmet {...config.head} />
    <Menu />
    <Route path="/" render={() => <Home />} exact />
  </div>
)
```

i.e. with no props passed

**Comment by faceyspacey** [comment]
if that doesnt work, yet when u use <Home /> without a Route wrapper it works, it makes little sense.

**Comment by dawidvdh** [comment]
so even with no props passed it returns the same mismatch, gonna logout the props with in render now.

**Comment by faceyspacey** [comment]
Also try this:

```js
<Route path="*" render={() => <Home />} exact />
```

and this:

```js
<Route path="/" render={() => <Home />} />
```

...maybe server-side React Router isn't working properly. Does it know its own path? ...one of these 2 options should just always render Home.

**Comment by faceyspacey** [comment]
another way to prove this hypothesis is to use another non-universal component and see if you get the mismatches? I.e. do u get mismatches when u *DONT* use universal?

**Comment by dawidvdh** [comment]
okay so oddly enough these two work:

```
<Route path="*" render={() => <Home />} exact />
<Route path="/" render={() => <Home />} />
```

oh god its probably got nothing to do with `react-universal-component`, so sorry man i think i just majorly wasted your time on a react-router issue... I think your correct about the path

**Comment by faceyspacey** [comment]
not a problem. i've done the same before. just last week even lol.

**Comment by faceyspacey** [comment]
but yea, make sure the memory history you create server side is done like at the top of the RFR docs here:

https://github.com/faceyspacey/redux-first-router/blob/master/docs/server-rendering.md#server-side-rendering-using-thunk

see how `initialEntries` receives an array of paths. If you're using express, that first path should be `request.path`.

**Comment by dawidvdh** [comment]
haha but thanks a lot man! really great support... anyways I'm gonna close this and not open another github issue in a year or so...

**Comment by faceyspacey** [comment]
Also, dont forget to read the latest on RFR (from yesterday): 

https://medium.com/faceyspacey/redux-first-router-data-fetching-solving-the-80-use-case-for-async-middleware-14529606c262

may inspire you to move to RFR sooner than later. It's been crafted with SSR as a top priority, and idiomatically makes all this seamless.

**Comment by dawidvdh** [comment]
Okay I really hope I am not embarrassing myself again but I have doubled checked the docs on react router with SSR and ensured that everything works with without `react-universal-component` and I have created an example based on a fork of on of your examples, you can see it [here](https://github.com/dawidvdh/flush-chunks-boilerplate-webpack-chunknames/tree/react-router-example) as it still seems to have the same render mismatch issue... let me know if I'm just being dumb again otherwise let me know if there's anyway i can assist, I will also try and debug my side.

**Comment by faceyspacey** [comment]
I'll get to this soon. I'm releasing 2.0 of this package today. please try once again with the new babel plugin (universal-import) when you get a chance.

**Comment by dawidvdh** [comment]
Hey thanks @faceyspacey, I have tried with upgraded dependancies but the problem still persists. But yeah I also haven't had time to try debug the situation, will let you know if I do though

**Comment by faceyspacey** [comment]
I got a chance to open it. I found the issue. There's 2:

1) you have to call `flushChunkNames` and `flushChunks` after `renderToString`. It was above it below an old commented out call to `renderToString`. I moved it so it looks like this now:

```js
export default ({ clientStats, outputPath }) => (req, res) => {
  // const app = ReactDOM.renderToString(<App />)
  const reactRouterContext = {}

  const component = ReactDOM.renderToString(
    <StaticRouter location={req.url} context={reactRouterContext}>
      <App />
    </StaticRouter>
  )
  const chunkNames = flushChunkNames()
  const { js, styles, cssHash, scripts, stylesheets } = flushChunks(clientStats, { chunkNames })

  console.log('PATH', req.path)
  console.log('CHUNK NAMES RENDERED', chunkNames)
  console.log('SCRIPTS', scripts)
  console.log('STYLESHEETS', stylesheets)
  console.log('ASSETS', clientStats.assetsByChunkName)

  res.send(
    `<!doctype html>
      <html>
        <head>
          <meta charset="utf-8">
          <title>react-universal-component-boilerplate</title>
          ${styles}
        </head>
        <body>
          <div id="root">${component}</div>
          ${js}
          ${cssHash}
        </body>
      </html>`
  )
}
```

2) the css chunk wasn't getting generated because you also imported it into the `main` chunk by way of the `Home` component at this line:

https://github.com/dawidvdh/flush-chunks-boilerplate-webpack-chunknames/blob/react-router-example/src/components/Home.js#L2

delete that line and removes application as the the `className` below, and you will now get an `Example.css` file.

**Comment by faceyspacey** [comment]
And by the way, none of this is a waste of my time. We've proven React Router works fine. Thanks for this.

**Comment by dawidvdh** [comment]
Thank you!!!

**Comment by faceyspacey** [comment]
@dawidvdh I don't suppose you'd be interested in making CodeSandBox like this one:

https://codesandbox.io/s/github/faceyspacey/redux-first-router-codesandbox?

showcasing Universal working React Router?? ...if u do i'll publish it in the docs.

**Comment by faceyspacey** [comment]
...bonus a github repo with SSR implementation.

**Comment by dawidvdh** [comment]
Hey @faceyspacey i would be super keen. I'll even do you one better, myself and a few people have been developing a boilerplate for power users that use your tools extensively... we'll probably be releasing within the next week, I will let you know as son as its up!

**Comment by dawidvdh** [comment]
@faceyspacey as promised our boilerplate https://github.com/madeagency/reactivity still working on the documentation, fixing up our code climate score and of course any and all pull requests are super welcome, Let us know what you think!

**Comment by faceyspacey** [comment]
super excited. we need this. i'll check it out.

**Comment by PaulBrunache** [comment]
@faceyspacey I'm experiencing an issue you described above in regards to react-router-dom. The root page loads fine, the first component loads fine but when i click the link to go to the next page, I have to refresh my browser for it to load. I can navigate to via direct url to the pages but just not client side it would appear. 

I download @dawidvdh 's react router fork of your universal demo. 
https://github.com/dawidvdh/flush-chunks-boilerplate-webpack-chunknames/tree/react-router-example

I'm not sure what's going wrong.

## App.js
`import React from 'react'
import universal from 'react-universal-component'
import Switch from 'react-router-dom/Switch'
import Route from 'react-router-dom/Route'
import Link from 'react-router-dom/Link'
import styles from '../css/App.css'
import Home from './Home'

const UniversalExample = universal((props) => import(`./${props.page}`))

const App = () => (
  <div>
    <nav className={styles.nav}>
      <ol>
      <li><Link to='/'>Static</Link> </li>
      <li><Link to='/test'>Test</Link> </li>
      <li><Link to='/example'>example</Link> </li>
      </ol>
    </nav>
  
    <Switch>
      <Route path='/' component={Home} exact />
      <Route path="/example" render={ ()=> <UniversalExample page="Example" />} />
      <Route path="/Test" render={ ()=> <UniversalExample page="Test" />} />
    </Switch>
  </div>
)

export default App
` 

## render.js
`
export default ({ clientStats, outputPath }) => (req, res) => {

  const reactRouterContext = {}
  
    const component = ReactDOM.renderToString(
      <StaticRouter location={req.url} context={reactRouterContext}>
        <App />
      </StaticRouter>
    )
  
    // HERE'S THE CORRECT PLACE TO PUT IT
    const chunkNames = flushChunkNames()
    const { js, styles, cssHash, scripts, stylesheets } = flushChunks(clientStats, { chunkNames })
  
    console.log('PATH', req.path)
    console.log('CHUNK NAMES RENDERED', chunkNames)
    console.log('SCRIPTS', scripts)
    console.log('STYLESHEETS', stylesheets)
    console.log('ASSETS', clientStats.assetsByChunkName)
  
    res.send(
      `<!doctype html>
        <html>
          <head>
            <meta charset="utf-8">
            <title>react-universal-component-boilerplate</title>
            ${styles}
          </head>
          <body>
            <div id="root">${component}</div>
            ${js}
            ${cssHash}
          </body>
        </html>`
    )
  }`

I might just try and work backwards and use your example instead unless I'm missing something from @dawidvdh fork
