### ISSUE TITLE
Aggregation of chuncks

### ISSUE THREAD

**Issue by chindris** [faceyspacey/react-universal-component#170]
Hello!

I am using the universal component in a project and I am wondering if there is a way to actually have an aggregation of chunks for the current page. So, let's say I have two components, componentA.js and componentB.js, instead of having those two chunks in separate files, on the page they are used, I just want to have them aggregated, let's say something like componentA+B_hash.js. Is this possible or maybe planned for the future?

**Comment by ScriptedAlchemy** [comment]
Oh yeah this is possible. But you don’t need RUC for it. You just need to mess with the optimization configuration within Webpack and how Webpack splits the code. 

RUC accepts an array of promises too, if you use the HOC, RUC renders the first module in the array but will load or can dynamically load other assets along with it


Use case. 

I have a slider, for mobile I use one that still needs jquery. So I pass in the slider via promise.all with a import() for my component to be rendered, and another import(‘jquery’)

I then can combine into dependency chains that can be loaded on demand 

Hope this helps, but your fundamental request might fall out the scope of my little plugin

**Comment by ScriptedAlchemy** [comment]
There’s also plugins like limitchunkcount
