### ISSUE TITLE
How to properly release a new version of app that uses react-universal-component?

### ISSUE THREAD

**Issue by braska** [faceyspacey/react-universal-component#177]
I successfully use react-universal-component in production, but I am faced with a problem related to releasing new versions of my app.

My case:
I have a released version of application. I open an app in a browser. Then I release a new version of app. After that I trigger loading of some component in opened app (that was opened before new release). And I am getting an error.

Looks like when I open app before release it loads `main.SOME_HASH.js`, that contains a list of chunks for lazy components. Each of this chunk contains hash in file name.

When I release new version of app, some (or all) hashes in file names of chunks can be changed. But because I opened app before release, `main.SOME_HASH.js` contains an old list of chunks. So when I trigger loading of component in my app, react-universal-component tries to load chunks for old version. And this chunk doesn't exist on server side any more (in docker image in my case).

As a solution, I see an ability to distinguish network error and 404 from server. In this case I can show error page to user if there is a network error, but if server returns 404 code while downloading chunk for lazy component I can trigger `window.location.reload()`, that will cause downloading new version of app (downloading new version of `main.SOME_NEW_HASH.js` that contains a new list of chunks).

So, I suggest to add response info (at least response code) to error that react-universal-component passes to ErrorComponent.

I am not 100% sure that this is right solution. Maybe anyone can suggest another option.

**Comment by ScriptedAlchemy** [comment]
Dude your deployments sound backwards. Docker containers shouldn’t matter at all. You don’t build them and boot them. You build one image and clone it three times. 

It sounds like, you are both running a webpack build and thebserver in production? Or doing a build per Instance? If a redeploy happens all those pads should scale down and back up, the only command is “start” and run from the built files

**Comment by ScriptedAlchemy** [comment]
Production shouldn’t have a build but just start from static files.

**Comment by braska** [comment]
Look like you don't understood me. I run `yarn build` as one of the command in Dockerfile. Docker images are building on CI, then pushing to image registry. After that CI script trigger deployment to Kubernetes via Helm.

So I don't try to build on boot time.

I found solution: https://spectrum.chat/react/general/how-to-handle-deployments-with-webpack-code-splitting~16dc5f85-0b4b-4eee-8693-066d82dcdc7f

The best option for me to store all versions of builds in separated storage (like S3). I will try to setup pushing chunks to S3 as one step of CI script.

**Comment by ScriptedAlchemy** [comment]
Ahhh apologies, yeah the best move is to point assets to a CDN- you can set the public path to be an external url. But I assume you know of this I'm not sure why you'd get 404s unless there's some cache holding onto old chunks which I doubt you'd want to serve to your clients

**Comment by braska** [comment]
I would like to avoid storing old chunks (storage is another one infrastructure element that can increase cost and requires maintenance). Best case scenario for me: reload page if it tries to download chunk that was presented in old docker container/image, but in current (new) running container not presented.

My question: how can I detect there 404 error returned for server for old chunk?

This is simplified version of my current implementation:
```jsx
const ErrorLoadingPage = ({ error }) => {
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    if (error && error.request) {
      window.location.reload();
    } else {
      setLoading(false);
    }
  });

  if (loading) {
    return <LoadingPage />;
  }

  return (
    <StyledMainTemplate>
      <Helmet>
        <title>Error while loading</title>
      </Helmet>
      <Wrapper>
        <p>Error occurred</p>
        <Button
          primary
          onClick={() => {
            window.location.reload(true);
          }}
        >
          Retry
        </Button>
      </Wrapper>
    </StyledMainTemplate>
  );
};
```

But the problem of this implementation that page will be reloaded even if there is no internet connection. User will see default browser page like this:
![image](https://user-images.githubusercontent.com/3268276/53289945-7186af00-37ae-11e9-9d90-ce075a8be0aa.png)

But I want to show ErrorLoadingPage if user lost internet connection and reload page only if 404 was returned from server.

It would be great if I have ability to replace `if (error && error.request) { ... }` statement with `if (error && error.response && error.response.code === 404) { ... }`.
