### ISSUE TITLE
Can you call 'clearChunks' *after* render has completed?

### ISSUE THREAD

**Issue by franjohn21** [faceyspacey/react-universal-component#178]
The examples and documentation call for invoking the `clearChunks` function before the React render has completed.
```js
  clearChunks()
  const app = ReactDOM.renderToString(<App />)
  const { js, styles, cssHash } = flushChunks(webpackStats, {
    chunkNames: flushChunkNames()
  })
```

I'm curious if there is any harm with calling `clearChunks` _after_ the react render has completed.
```js
  const app = ReactDOM.renderToString(<App />)
  const { js, styles, cssHash } = flushChunks(webpackStats, {
    chunkNames: flushChunkNames()
  })
  clearChunks()
```

This is how, for example `react-document-title` works: https://github.com/gaearon/react-document-title#server-usage

**Comment by eliseumds** [comment]
If renderToString throws an exception for some reason, your app won't have a chance to clear the chunks up, so it's safer to do it before.

**Comment by ScriptedAlchemy** [comment]
@eliseumds great answer that I didn't even think of!

I suppose you could have clear chunks after, just wrap it in a try catch :)
