### ISSUE TITLE
Async loading with sagas and reducers

### ISSUE THREAD

**Issue by GuillaumeCisco** [faceyspacey/react-universal-component#18]
Hello, I'm struggling with the universal component to load asynchronous reducers and sagas for a react component.
I'd like to import my component and for that import reducers and sagas just before.
I use `injectReducer` and `injectSaga` from respectively `redux-injector` and `redux-sagas-injector`.

I've tried with:
```javascript
import React from 'react';
import universal from 'react-universal-component';
import {injectReducer} from 'redux-injector';
import {injectSaga} from 'redux-sagas-injector';

const Component = universal(
    props => {
        const sagas = [import('./sagas')],
            reducers = [import('./reducers/index'), import('../settings/reducers')];

        const all = Promise.all([...sagas, ...reducers]);
        return all.then((values) => {
            injectSaga('notebook', values[0].default);
            injectReducer('notebook', values[1].default);
            injectReducer('settings', values[2].default(window.localStorage));

            return import('./component');
        });
    }
```
I get an error `Error: load is not a function`. Indeed Promise.all returns a promise that does not implement the `.load` method. And as I discovered `import('./component')` returns an **object** with several methods (which includes `load`).
I've also tried to put the code retrieving the sagas and the reducers in the `onLoad` method, but the component is already loaded. What I'd want is a `onBeforeLoad`, is it achievable?
I also tried in a thunk with the routesMap with no more success.
Tried with `(props, cb) => require.ensure([], require => cb(null, require('./Foo')))` but I get an error : `cb is undefined`...

Tell me if I'm missing something huge.

**Comment by faceyspacey** [comment]
im gonna have to respond more in depth tomorrow, but here's the quick "HUGE" thing:

the first argument can only import one thing. The babel plugin won't be able to play well with that. It's also not efficient, even though you're doing parallel loading. In the future we will support multiple imports, but it's far more challenging than one at a time. 

So what you can do is make one component that imports all these extra things, and then re-exports them. And then just have one module imported like this:

```js
universal(import('./component'), {
   onLoad: module => {
      injectSaga('notebook', module.notebookSaga)
      injectReducer('notebook', module.notebookReducer)
      injectReducer('settings', module.settings(window.localStorage))
  },
  // key: 'default' -- this is the default, and what the component will be, i.e. module.default
})
```

On load will fire before the component is rendered. But the thing is you probably used `onLoad` to trigger another promise/async thing, which would then come after render. You have to treat `onLoad` synchronously and use what was discovered in the async phase.

I hope that helps.

**Comment by GuillaumeCisco** [comment]
Thank you very much @faceyspacey.
I thought I had to do something like that, but did not correctly understand it fully. A lot new things ^^
Your comment made a "pop" in my brain ^^

I've came with two ways of achieving it.

One with a React Component handling:
```javascript
import React from 'react';
import universal from 'react-universal-component';
import {injectReducer} from 'redux-injector';
import {injectSaga} from 'redux-sagas-injector';

const UniversalComponent = universal(import('./components/Notebook'),
    {
        loading: () => <div>Loading notebook ...</div>,
    });

class PreloadedNoteBook extends React.Component {
    state = {
        loaded: false,
    };

    componentWillMount() {
        const sagas = [import('./sagas')],
            reducers = [import('./reducers/index'), import('../settings/reducers')];
        Promise.all([...sagas, ...reducers])
            .then(([sagas, notebook, settings]) => {
                injectSaga('notebook', sagas.default);
                injectReducer('notebook', notebook.default);
                injectReducer('settings', settings.default(window.localStorage));

                this.setState({loaded: true});
            });
    }

    render() {
        return this.state.loaded ? <UniversalComponent/> : null;
    }
}

export default props => <PreloadedNoteBook/>;
```
It prevents the component to be rendered before everything is correctly injected. It can also be connected to redux for using condition redendering and import.

The other way is not importing a react component but a file as you said will import all I need:
component.js:
```javascript
export sagas from './sagas';
export notebook from './reducers/index';
export settings from '../settings/reducers';
import Notebook from './components/Notebook';

export default Notebook;
```
and the loading:
```javascript
const Universal = universal(import('./preload'), {
    loading: () => <div>Loading preload ...</div>,
    onLoad: module => {
        injectSaga('notebook', module.sagas);
        injectReducer('notebook', module.notebook);
        injectReducer('settings', module.settings(window.localStorage));
    },
    // key: 'default' -- this is the default, and what the component will be, i.e. module.default
});

export default props => <Universal/>;
```

I still don't know if one is better than another. I'm still experimenting, but hope it helps discover new things ;)
Thank you again.

**Comment by faceyspacey** [comment]
Yea, the second one is the "Universal way."

It will inject all that stuff before the render. the `loading` component will show, the stuff will be injected, and then it will render the imported component for the first time. 

Nice job.
