### ISSUE TITLE
Server always returns "loading"

### ISSUE THREAD

**Issue by Dagniele** [faceyspacey/react-universal-component#182]
Hi,
I know there are several issues about this, but none of the solutions work for me, I have the plugin LimitChunkCountPlugin, I have the exact same externals like in the example, disabled DllReferencePlugin, still no difference, the server return "loading" and as a double symptom I receive "Warning: Expected server HTML to contain a matching div in div" because of the difference, but, I tried the demo and it has the exact same problem:

![Selection_021](https://user-images.githubusercontent.com/7351794/54259310-9a0bf880-4565-11e9-92eb-2c2da43d2233.jpg)

Any idea how to fix it?

I'm using version 4.0.0 of react-universal-component and same for babel plugin

**Comment by ScriptedAlchemy** [comment]
check the closed issues - its been solved many times. Ill update the demo as well. 

Pass the import to universal as a function <UniversalComponent page={import()}/>

when passing as a string, its harder to flush the chunknames out because of how the naming conventions are. 

if you are passing the page prop as a string then that is likely the cause of the issue.

**Comment by ScriptedAlchemy** [comment]
Pushing updates to universal demo momentarily

**Comment by Dagniele** [comment]
Hi again, I just checked the demo, and I just switched to pass a function to universal, but same result, this is how I use it:

`
import universal from 'react-universal-component';
import Placeholder from './svg-icons/Placeholder';

function getLazyComponent(name) {
    return universal(() => import(\`./svg-icons/${name}\`), { loading: Placeholder, ignoreBabelRename: true });
}

const ActionAssessment = getLazyComponent('ActionAssessment');
const Add = getLazyComponent('Add');
const AllMatches = getLazyComponent('AllMatches');
...
`

**Comment by Dagniele** [comment]
Also tried with this way:

```
const icons = {
    'action-assessment': 'ActionAssessment',
    'add': 'Add',
    'all-matches': 'AllMatches',
    ...
};

export const LazyIcon = universal(
    ({ name }) => import(`./svg-icons/${icons[name]}`),
    {
        loading: Placeholder,
        ignoreBabelRename: true,
    }
);
```

**Comment by Dagniele** [comment]
on server becomes this after webpack (in dev mode):

```
const LazyIcon = react_universal_component__WEBPACK_IMPORTED_MODULE_2___default()((_ref) => {\n  let name = _ref.name;\n  return babel_plugin_universal_import_universalImport__WEBPACK_IMPORTED_MODULE_1___default()({\n    id: \"./svg-icons/\",\n    path: () => path__WEBPACK_IMPORTED_MODULE_0___default.a.join(__dirname, `./svg-icons/${icons[name]}`),\n    resolve: () => /*require.resolve*/(__webpack_require__(\"../sir-components/src/svg-icons/svg-icons weak recursive ^\\\\.\\\\/.*$\").resolve(`./${icons[name]}`)),\n    chunkName: () => `svg-icons/${icons[name]}`\n  });\n}, {\n  loading: _svg_icons_Placeholder__WEBPACK_IMPORTED_MODULE_3__[\"default\"],\n  ignoreBabelRename: true\n});\n\n\n/* WEBPACK VAR INJECTION */}.call(this, \"/\"))\n\n//# sourceURL=webpack:///../sir-components/src/svg-icons/index.js?");
```

**Comment by ScriptedAlchemy** [comment]
Hmm can you put a repo up? 

Also are these JavaScript icons you are loading or SVG?

**Comment by Dagniele** [comment]
First of all thanks for the help, tomorrow I'll try to setup a mini version to post as a repo. The icons are svg react components, so yes javascript icons.

**Comment by Dagniele** [comment]
I could fix the error, it took 2 days, literally, and it was really simple, I just had to remove babelServer: true on babel config for the server, but because of the babel cache even if I tried that several times I could see it was fixed only after I removed the babel cache in node_modules.

Thanks very much for the help anyway :)
