### ISSUE TITLE
Double Rendering on example and test apps

### ISSUE THREAD

**Issue by quantumninja** [faceyspacey/react-universal-component#19]
Hey this is awesome and so glad you solved this issue. I've tried running both your React Universal Component Demo and a modified version of @DominicTobias Universal React.

[https://github.com/quantumninja/universal-react](url)

Not sure yet why but I'm seeing the server rendered version come up and then the app bootstrap and re render over the top. Any idea why this is happening?

**Comment by quantumninja** [comment]
Also new webpack release is out on NPM

**Comment by faceyspacey** [comment]
ok, well now it will just work. ..let me know if you're still having the problems. There is quite a few things to setup. But that's the cost of the "frameworkless approach."

The next thing that comes out will have a `debug` mode which can indicate what your problems might be.

Potential issues are likely 
-`externals` are not actually properly configured to exclude `react-universal-component` and `webpack-flush-chunks` on the server
- or you're putting `react-universal-component` in the autdll bundle, which runs the code outside of the normal webpack context, the client doesn't think it can synchronously render it. 

In both cases, the code won't know it's running in webpack, which it needs to know. And it simply won't have access to webpack-specific functions.

**Comment by quantumninja** [comment]
Still having problems, I got it working earlier today and now it's coming back with 

`return Promise.all([import( /* webpackChunkName: 'containers/Home' */'./containers/Home'), (0, _importCss3.default)('containers/Home')]).then(function (proms) {
                        ^^^^^^

SyntaxError: Unexpected token import`

I haven't got webpac-flush-chunks on the server so will try installing that but it was working without it earlier.

**Comment by faceyspacey** [comment]
`import` isn't being compiled if that's the issue.

**Comment by quantumninja** [comment]
Yeah looks like it. I managed to get it working sort of. If I pull out the import statement and then run the server it loads up fine. If I put it back in and recompile it then starts working but still not sure why. At this point thinking I will try and build my own boilerplate with this tomorrow and see if I can get it working that way.

**Comment by faceyspacey** [comment]
yea, isolate is the best way. it sounds like you have a pretty complex setup.

**Comment by quantumninja** [comment]
Another quick question, when the demo loads it server renders but then also loads the chunk for that page as well. Is that meant to happen? I thought it would have just loaded the server rendered html and then the app bundle?

**Comment by faceyspacey** [comment]
you'll see it once in the network tab. it has to be loaded no matter what as the raw javascript isn't embedded.

if you're seeing it a second time, then that's a problem.

the idea is this: if it wasn't handled synchronously, `main.js`, `vendor.js` etc would have to load, be parsed, evaluated, and then make a complete render, at which point the additional chunk would be loaded. So it's the difference of:

```js
Promise.all([main.js, vendor.js, chunks.js]).then(render)

// vs

Promise.all([main.js, vendor.js])
   .then(partiallyRender)
   .then(() => load(chunks.js)
   .then(completeRender)
```

sequential vs complete parallel.

**Comment by quantumninja** [comment]
Not seeing the chunk show up twice I'm just seeing the chunk show up after render. See my output below:
```
main.js | 200 | script | (index) | 1.3 MB | 134 ms
-- | -- | -- | -- | -- | --
main.css | 200 | stylesheet | (index) | 12.8 KB | 12 ms
localhost | 200 | document | Other | 2.0 KB | 10 ms
faceyspacey-white-logo.png | 200 | png | (index) | 5.6 KB | 145 ms
bootstrap.js | 200 | script | (index) | 29.7 KB | 5 ms
__webpack_hmr | 200 | eventsource | Other | 20.9 KB | 1.90 s
Foo.js | 200 | script | (index) | 1.9 KB | 6 ms
Foo.css | 200 | stylesheet | (index) | 523 B | 12 ms

```

**Comment by faceyspacey** [comment]
are you seeing a loading component? set minDelay to a value like 1000 so you can be sure that the universal component goes through a loading stage. it won't go through the stage if it has the component to require synchronously.

...also, it may show up after main.js in the network tab, but the page will be smart enough to not evaluate it in any order other than what you specified on the page.

**Comment by quantumninja** [comment]
No it's all coming up on initial load and I can see the content in the page source as well.

**Comment by faceyspacey** [comment]
I don't understand. Does that mean it's working or not? Do you see loading...

**Comment by quantumninja** [comment]
Sorry speaking Australian there :). It's working as intended.

**Comment by faceyspacey** [comment]
Excellent!
