### ISSUE TITLE
Support React 16.9.0 warning componentWillMount

### ISSUE THREAD

**Issue by maystrenkoYurii** [faceyspacey/react-universal-component#190]
![Снимок](https://user-images.githubusercontent.com/23016311/62898267-c2d72a80-bd5d-11e9-899e-d09ffef074ec.JPG)

**Comment by tstirrat15** [comment]
What version are you using? `componentWillMount` is not currently present in master.

**Comment by believer-ufa** [comment]
I'm also have such error message, maybe it did throw from another libraries.

**Comment by ScriptedAlchemy** [comment]
Will mount is gone in v4
