### ISSUE TITLE
How to remove "Loading..." in react-universal-component?

### ISSUE THREAD

**Issue by swham-ai** [faceyspacey/react-universal-component#196]
Currently I am using react-universal-component with code-splitting...

Everytime I switch page it shortly displays "Loading..." like 0.1 second then render the proper page.

I just want to delete "Loading..." so that there is no blinking while switching any page. How can I do that with react-universal-component? is there any example?

**Comment by cdoublev** [comment]
You can override the default component shown with a component that returns null.

```js
  const loadingFn = ({ page }) => import(`./${page}`)
  const loadingOptions = {
    loading: () => null,
}
const UniversalComponent = universal(loadingFn, loadingOptions)
```

Alternatively, you can use `loadingTransition: true` (see README).

**Comment by online0227** [comment]
Thank you very much it helped 

```
const loadingOptions = {
  loading: () => null,
  loadingTransition: false
}

const UniversalComponent = universal(props => import(`./${props.page}`), loadingOptions)
```

**Comment by swham-ai** [comment]
Thank you very much it helped

```
const loadingOptions = {
  loading: () => null,
  loadingTransition: false
}

const UniversalComponent = universal(props => import(`./${props.page}`), loadingOptions)
```
