### ISSUE TITLE
Data-react-id missing on loader

### ISSUE THREAD

**Issue by jamesjjk** [faceyspacey/react-universal-component#2]
Great component! But for the loader the data-react-id is missing causing a mismatch.

**Comment by faceyspacey** [comment]
what boilerplate are you using?

**Comment by jamesjjk** [comment]
No boilerplate, using webpack import with a custom loader.

**Comment by faceyspacey** [comment]
if u provide me a minimal example or even paste the following code I can likely find the problem:

- code where you define the `<UniversalComponent />`
- where in your react tree it's used
- your server side render code (where ur webpack-flush-chunks stuff is)
- the corresponding webpack config
-babelrc

if u paste the relevant parts, that will save u time from having to make a minimal example repo. 

...u've looked into [Webpack Flush Chunks](https://github.com/faceyspacey/webpack-flush-chunks) right?

Universal rendering won't work without it.

**Comment by faceyspacey** [comment]
Here are the boilerplates:

https://github.com/faceyspacey/webpack-flush-chunks#boilerplates

**Comment by jamesjjk** [comment]
@faceyspacey All good and fixed! Very cool plugin combined with stream of https://github.com/FormidableLabs/rapscallion makes it a very fast experience for a huge react site!
