### ISSUE TITLE
Production mode and adding new js files

### ISSUE THREAD

**Issue by Kurdakov** [faceyspacey/react-universal-component#20]
I tried your great code,

while not directly related to your code, but it relates to obvious common use case which might be possible with your universal-component:

a user assembles a new page from components, cms  generates complete code for new page ( new js component ), puts it into src\components, 
now it is time to view it in browser, 

in dev mode a new page would be picked up by webpack, compiled and can be referenced from other existing pages (let's say new page name is fetched from list of available pages from cms by ajax call and added to /src/utils/index.js pages variable in your example app).

but it does  not work in production - adding a new component as a js file will not cause compilation ( as new files are not watched ) and restart of yarn/webpack is required to compile new page/component.

and my question is - if it is at all possible to realize that cms scenario in production mode?

**Comment by faceyspacey** [comment]
I think there may be support for `module.hot` in production. I'd research that. I remember it being said that it was kind of an unproven/untested solution, but it is possible. At least in older webpack's. I'd be very interested to find out too. It's an interesting way to update your live apps quickly.

**Comment by faceyspacey** [comment]
let me know if u ever found out if webpack in production can HMR properly.

the issue may simply be that `module.hot` is being compiled out, or that it's guarded by `process.env.NODE_ENV === 'development'`, in which case it will also be compiled out.
