### ISSUE TITLE
Text Content Did Not Match

### ISSUE THREAD

**Issue by geroylaurence** [faceyspacey/react-universal-component#221]
Hi,
    I am using the old version of "react-universal-component (2.0)".
    Now I am migrating the latest version but when I apply the react-router-dom I got this error.
    
    
![image](https://user-images.githubusercontent.com/48232303/102255877-a5176800-3f45-11eb-876f-cbecfcb4ef7e.png)

Can you show me how to apply react-router-dom with react-universal-component?

**Comment by cdoublev** [comment]
Hi,

The following works for me:

**server/render.js**

```js

import { flushChunkNames } from 'react-universal-component/server'
import App from '../src/universal/app'
import { StaticRouter } from 'react-router-dom'
import flushChunks from 'webpack-flush-chunks'
import { renderToString } from 'react-dom/server'

const render = ({ clientStats }) => async (req, res) => {

    try {

        const context = {}
        const app = renderToString(<StaticRouter location={req.url} context={context}><App /></StaticRouter>)
        const { js } = flushChunks(clientStats, { chunkNames: flushChunkNames() })

        return res.send(`
            <html lang="en">
                <body>
                    <div id="app">${app}</div>
                    ${js}
                </body>
            </html>
        `)

    } catch (error) {
        console.error(error)
        return res.status(500).end('Server render error')
    }
}

export default render
```

**src/index.js**

```js

import { BrowserRouter } from 'react-router-dom'
import App from './universal/app'
import { hydrate } from 'react-dom'

hydrate(<BrowserRouter><App /></BrowserRouter>, app)
```

**src/universal/app.js**

```js

import { Switch, Route, Link } from 'react-router-dom'
import { StrictMode } from 'react'
import { hot } from 'react-hot-loader/root'
import universal from 'react-universal-component'

const loadingFn = ({ page }) => import(`./${page}`)
const UniversalComponent = universal(loadingFn)

const App = () =>
    <StrictMode>
        <div>
            <nav>
                <ul>
                    <li><Link to="/">Home</Link></li>
                    <li><Link to="/about">About</Link></li>
                    <li><Link to="/users">Users</Link></li>
                </ul>
            </nav>
            <Switch>
                <Route exact path="/"><UniversalComponent page='home' /></Route>
                <Route path="/about"><UniversalComponent page='about' /></Route>
                <Route path="/users"><UniversalComponent page='users' /></Route>
            </Switch>
        </div>
    </StrictMode>

export default hot(App)
```

Do you want to access to the full demo on Github?

**Comment by geroylaurence** [comment]
> Hi,
> 
> The following works for me:
> 
> **server/render.js**
> 
> ```js
> import { flushChunkNames } from 'react-universal-component/server'
> import App from '../src/universal/app'
> import { StaticRouter } from 'react-router-dom'
> import flushChunks from 'webpack-flush-chunks'
> import { renderToString } from 'react-dom/server'
> 
> const render = ({ clientStats }) => async (req, res) => {
> 
>     try {
> 
>         const context = {}
>         const app = renderToString(<StaticRouter location={req.url} context={context}><App /></StaticRouter>)
>         const { js } = flushChunks(clientStats, { chunkNames: flushChunkNames() })
> 
>         return res.send(`
>             <html lang="en">
>                 <body>
>                     <div id="app">${app}</div>
>                     ${js}
>                 </body>
>             </html>
>         `)
> 
>     } catch (error) {
>         console.error(error)
>         return res.status(500).end('Server render error')
>     }
> }
> 
> export default render
> ```
> 
> **src/index.js**
> 
> ```js
> import { BrowserRouter } from 'react-router-dom'
> import App from './universal/app'
> import { hydrate } from 'react-dom'
> 
> hydrate(<BrowserRouter><App /></BrowserRouter>, app)
> ```
> 
> **src/universal/app.js**
> 
> ```js
> import { Switch, Route, Link } from 'react-router-dom'
> import { StrictMode } from 'react'
> import { hot } from 'react-hot-loader/root'
> import universal from 'react-universal-component'
> 
> const loadingFn = ({ page }) => import(`./${page}`)
> const UniversalComponent = universal(loadingFn)
> 
> const App = () =>
>     <StrictMode>
>         <div>
>             <nav>
>                 <ul>
>                     <li><Link to="/">Home</Link></li>
>                     <li><Link to="/about">About</Link></li>
>                     <li><Link to="/users">Users</Link></li>
>                 </ul>
>             </nav>
>             <Switch>
>                 <Route exact path="/"><UniversalComponent page='home' /></Route>
>                 <Route path="/about"><UniversalComponent page='about' /></Route>
>                 <Route path="/users"><UniversalComponent page='users' /></Route>
>             </Switch>
>         </div>
>     </StrictMode>
> 
> export default hot(App)
> ```
> 
> Do you want to access to the full demo on Github?

Hi cdoublev, thanks for this response, I will check and follow this, and yes how can I access the full demo on Github?

**Comment by cdoublev** [comment]
https://github.com/cdoublev/ruc-react-router

**Comment by geroylaurence** [comment]
> https://github.com/cdoublev/ruc-react-router

going to check on this, thank you

**Comment by cdoublev** [comment]
Did you solve your issue?

**Comment by geroylaurence** [comment]
> Did you solve your issue?

hello, yes, I just follow this solution you showed, and It's working now.
