### ISSUE TITLE
Where is 4.5.0 version changelog?

### ISSUE THREAD

**Issue by SuperOleg39** [faceyspacey/react-universal-component#223]
Hello!

After delete my lock file, and install modules from scratch, i see `react-universal-component@4.5.0` in my dependencies.

But i can't see `4.5.0` version in this repository tags / branches / etc.

Maybe it was a mistake publish?

**Comment by cdoublev** [comment]
Hello,

`v4.5.0` has been published on npm while the corresponding tag was not pushed into Github. There is also a jump from `v4.0.1` to `v4.5.0`. From his own words, the current maintainer of this package is lacking time to properly maintain it and new maintainer(s) are more than welcome.

**Comment by SuperOleg39** [comment]
Got it, thank you!
