### ISSUE TITLE
Error swallowed in `requireById`

### ISSUE THREAD

**Issue by otajor** [faceyspacey/react-universal-component#24]
I was getting weird behaviour where one of my components was being rendered on the server as its Loading component every time, without any errors. I took a look at the source code and put some logs in and was pretty confused because it seemed like errors requiring the component would be caught in the try/catch here: 
https://github.com/faceyspacey/react-universal-component/blob/master/src/index.js#L76-L81
But there was no error in the universal-component state.

I followed the breadcrumbs back to where the component was originally being imported, which turned out to be here: https://github.com/faceyspacey/react-universal-component/blob/master/src/utils.js#L29

After I wrapped this (`return __webpack_require__(id)`) in a try / catch, I finally got a look at the error, which was just a rogue `window is not defined` in a nested child component of the component that was meant to be rendered.

The error gets swallowed by the try / catch here: https://github.com/faceyspacey/react-universal-component/blob/master/src/utils.js#L19
Don't know if there's a reason for it being this way, but it meant that debugging the error took a lot longer than it might have. Let me know if I can be any more help (happy to take a crack at a PR) - hugely appreciate all the work that went into this package!

**Comment by faceyspacey** [comment]
very important find. i personally hate how promises eat things in various packages. i really would hope my own isn't one of them.

...I guess the challenge is that if RUC catches it, and rethrows it, u end up with the same problem.

Can you add an `onError` callback (u can provide it as a prop to the component itself in jsx), and let me know if that makes the visibility of these errors more standard?

Also, would catching, throwing a warning, and rethrowing solve this?

**Comment by otajor** [comment]
> would catching, throwing a warning, and rethrowing solve this

That's pretty much what I ended up doing ([utils.js#L24](https://github.com/faceyspacey/react-universal-component/blob/master/src/utils.js#L24)):
```javascript
export const requireById = (id: Id): ?any => {
  if (!isWebpack() && typeof id === 'string') {
    return module.require(id)
  }
  try {
    return __webpack_require__(id)
  } catch (e) {
    console.log(e)
    throw e
  }
}
```
Re-throwing is a bit pointless unless you also re-throw in the next catch block up (and possibly beyond?), but a warning would solve this as far as my case went.

I just had a go with the `onError` callback as well but it didn't pick up the error.

**Comment by faceyspacey** [comment]
yea, the re-throwing thing didnt seem like the right idea to me when i considered it. ...here's the thing about what goes on here--its not necessarily an error. sync requiring falls back to async. and that's a natural thing that happens. so it makes it harder to figure out what happens there.

i want to add a debug mode for all these tools--so perhaps that can solve it, and make it make more sense to do some additional logging/warning here.

**Comment by faceyspacey** [comment]
closing as eventual planned debug mode will help with all this stuff.
