### ISSUE TITLE
Server renderung doesn't work with common chunks

### ISSUE THREAD

**Issue by codepunkt** [faceyspacey/react-universal-component#26]
Suppose we have three universal components named A, B and C, with A and C using `lodash`.

with an entry chunk named `app` and a commons chunk configuration like this
```javascript
new webpack.optimize.CommonsChunkPlugin({
  name: 'manifest',
  minChunks: Infinity,
}),
new webpack.optimize.CommonsChunkPlugin({
  children: true,
  async: 'usedTwice',
  minChunks: 2,
})
```

webpack outputs these files:
- manifest.js
- app.js
- A.js
- B.js
- C.js
- usedTwice.js

When server rendering using `redux-first-router`, `flushChunkNames` returns `['B']` rendering a route with B so the server renders script tags in this order: manifest, B, app. All is fine.

When server rendering a route with A or C instead, `flushChunkNames` returns `['A']` or `['C']` respectively, but omits `usedTwice` so the server renders script tags in this order: manifest, A/C, app.

In the second case, the commons chunk `usedTwice` is ignored in server side rendering. Server should instead render script tags in this order: manifest, usedTwice, A/C, app.

**Comment by faceyspacey** [comment]
I'm on my phone at this very moment but check the dual-import plugin. Somebody posted an issue about this yesterday. I forget if it's open or closes

**Comment by codepunkt** [comment]
Will check, thanks :)

**Comment by faceyspacey** [comment]
I'm gonna close this one out, but here's the issue I meant:

https://github.com/faceyspacey/webpack-flush-chunks/issues/21

it wasn't in the dual-import repo. my bad. Let me know if it provides solutions to your problem. Obviously it would be nice to automate the things done there, but a minor PR emerged from it and some manual code u can paste that should make it easier.
