### ISSUE TITLE
flow errors

### ISSUE THREAD

**Issue by chapati23** [faceyspacey/react-universal-component#27]
when using this module in a flow-activated component there are a bunch of type errors. flow v0.52.0

![image](https://user-images.githubusercontent.com/117495/29454246-ba8d5c6e-840c-11e7-98c3-91d4a764ce15.png)

**Comment by faceyspacey** [comment]
Funny thing is I flow typed but haven't used it with flow. The issue is that the babel plugin transforms it to what's expected. It should still pass tho. Just suppress it for now

**Comment by lizell** [comment]
You could add something like this to your `.flowconfig`:
```
[ignore]
<PROJECT_ROOT>/node_modules/react-universal-component/.*\.flow
```

**Comment by chapati23** [comment]
yup, that's exactly what we're doing. thanks @lizell :)

**Comment by lizell** [comment]
Great! I had the exact same problem, so thought I'd share!
