### ISSUE TITLE
static preload() function doesn't work on server-side 

### ISSUE THREAD

**Issue by nikopavlica** [faceyspacey/react-universal-component#31]
On server-side I'd like to statically resolve the Universal component, so i can access some static methods underneath (data-fetching prior react render).

For this, i tried using `universal.preload(props, context)`, but it fails because it tries to fetch the module asynchronously:
```
Stack: TypeError: load is not a function
    at ./node_modules/react-universal-component/dist/requireUniversalModule.js:110:25
```

I believe it would be good if this method would simply return resolved/rejected promise on server side.

If you think it makes sense, I'll gladly make a PR.

**Comment by MartinCerny-awin** [comment]
@nikopavlica I am trying to accomplish something similar. Can you please share an example how did you do data-fetching before rendering?

**Comment by nikopavlica** [comment]
This is a bit of an off-topic question, but I'm a good guy :)

I don't have the code publicly accessible, but the logic is following:
I have a react HOC that:
- has static definition for (async) endpoints
- exposes static function that fetches all its data (eg `prefetch()`)
- exposes static function which allows you to fetch data for all children (eg. `prefetchChildren()`)
- in runtime it feeds the responses as props to the wrapped component

When prefetching, all responses (promises) are stored into some context object, which is then fed to the react context provider and in turn used by the same async HOC (so prefetched responses are actually used in the render cycle)

I use the static `preload()` function of the react-universal-component to statically define the correct child component in the `prefetchChildren()` static function so i can prefetch the data required by the components that are behind the codesplit.

Maybe now there are some better and more simpler ways to do it... I haven't follow this aspect of react, since i needed this almost two years ago and there was nothing like it on 'the marked' :)

**Comment by eliseumds** [comment]
Same thing here.
