### ISSUE TITLE
Better dynamic pathing

### ISSUE THREAD

**Issue by shomanishikawa** [faceyspacey/react-universal-component#33]
We have a large app with many components, and would like to create a directory for each one.

Something like `/components/hero/index.js` or `/components/hero/hero.js` (preferred)

Unfortunately when we run something like the following:

```javascript
const UniversalComponent = universal((props) => {
  return import(`src/components/${props.type}/${props.type}`)
});
```

webpack names the chunk `src/components/hero-hero`, so ssr breaks. I saw a related issue about this, and it seems to be an issue on webpack's side - (https://github.com/webpack/webpack/issues/5575)

Currently, because our folder structure will be consistent, we are thinking of changing the line you referenced in the webpack issue (https://github.com/faceyspacey/webpack-flush-chunks/blob/master/src/flushChunks.js#L206):

```javascript
const chunk = assets[chunkName] || assets[chunkName + '-']
```
to something like:
```javascript
// replace last instance of `/` with a `-`
// (not actual implementation. just base example)
chunkName = chunkName.replace(/\/([^/]*)$/,'-'+'$1');
const chunk = assets[chunkName] || assets[chunkName + '-']
```

while this works, we realize how janky it is and don't want to rely on it.

Is there any way we can accomplish a more organized app architecture with each dynamic component being housed in its own directory?

**Comment by faceyspacey** [comment]
Ultimately webpack create chunks for every possible entry point. I'm basically only recommending U create a folder of entry points from now on. Keep ur structure but then create an async folder and import from there. It's the best way, and very worth it because of the great performance gains.

**Comment by shomanishikawa** [comment]
Thanks so much for the response.!

I've tried to follow your advice - I've kept my folder structure the same, so I have `src/components/hero/hero.js`, `src/components/threeup/threeup.js`, etc.

From there, i've created an `src/components/async/` directory with files like `src/components/async/hero.js`, etc.

My `async/hero.js` file simply imports the actual component files, and exports it like so:
```js
export {default} from 'src/components/hero/hero';
```

That way, my universal import will be something like the following:
```js
const UniversalComponent = universal((props) => {
  return import(`src/components/async/${props.type}`)
});
```

This is working functionally, and just want to make sure it is in line with what you were suggesting.

**Comment by faceyspacey** [comment]
bingo. i know, i hate those extra files too, but it's basically the only way to avoid creating unnecessary chunks. 

now that said, i havent done it, but u may be able to use the context-replacement plugin to tell webpack to skip some files:

https://webpack.js.org/plugins/context-replacement-plugin/

just a thought if u too are annoyed by the extra files.

**Comment by shomanishikawa** [comment]
thanks! will look into it and will report back if I come up with anything.

**Comment by joaovieira** [comment]
Did not know of that `ContextReplacementPlugin`! Was doing the same thing (separate folders) before, but after some tries I managed to keep everything in a single folder:

```
/modules/a/index.js
/modules/a/components/**/*
/modules/a/reducer.js
...
/modules/b/index.js
/modules/b/components/**/*
/modules/b/reducer.js
...
/modules/c/index.js
/modules/c/components/**/*
/modules/c/reducer.js
...
```

With a dynamic import like:

```js
const async = moduleName => import(`./modules/${moduleName}`);
```

And webpack config:

```js
new webpack.ContextReplacementPlugin(/modules/, /^\.\/[^\/]*$/)
```

That basically says to only match the top level path, which automatically defaults to `./index.js`. I.e.:

Given the folder:

```
/modules/a/index.js
/modules/a/components/**/*
/modules/a/reducer.js
```

it only matches `.a`, which resolves to `.a/index.js`
