### ISSUE TITLE
Loading component displayed even when loadingTransition is set to false

### ISSUE THREAD

**Issue by spadgeaki** [faceyspacey/react-universal-component#35]
Hello, thank you for doing awesome work! I am using universal component with redux-first-router in my latest project and its simply a joy to work with.

My layouts (different pages) are simple and while switching between them loading component flashes in for just a split of a second. I was happy to find an option loadingTransition, I set it to false but Loading component is still there. Am I missing something in implementation?

```
import React from 'react'
import universal from 'react-universal-component'

export default ({ page }) => {
    const Component = components[page] || NotFound
    return <Component />
}

const NotFound = () =>
    <div>
        PAGE NOT FOUND - 404
    </div>

const components = {
    Home: universal(() => import('layout/Home'), {
        loadingTransition: false
    }),

    Apps: universal(() => import('layout/Apps'), {
        loadingTransition: false
    }),

    About: universal(() => import('layout/About'), {
        loadingTransition: false
    }),

    NotFound
}
```

**Comment by faceyspacey** [comment]
Glad you are enjoying the tools.

That option is only for when you use dynamic expressions for your import. Not when you do static imports for multiple HoCs.

Your best option is to use the minDelay option. And you probably want to use dynamic expressions to import multiple components from a single universal hoc.
