### ISSUE TITLE
flushChunkNames doesn't know async chunk from CommonsChunkPlugin

### ISSUE THREAD

**Issue by jepezi** [faceyspacey/react-universal-component#37]
Hi again,

Congrats on V2. Looks solid! However, I run into some problems with CommonsChunkPlugin.

I've added CommonsChunkPlugin with [`async: true`](https://webpack.js.org/plugins/commons-chunk-plugin/#extra-async-commons-chunk) to `client.prod.js` in your [universal-demo](https://github.com/faceyspacey/universal-demo).

```js
// in client.prod.js plugins array, add this.
...
new webpack.optimize.CommonsChunkPlugin({
      children: true,
      async: true,
      minChunks: 2
}),
```

This config will create new chunk containing `Common` and load it on demand.
```js
// Add Common.js
import React from 'react'

export default () =>
  <div>
    <span>COMMON!!</span>
  </div>

```
Then in `Bar.js` and `Baz.js`, just render <Common /> after span.

```js
// Bar.js
import React from 'react'
import styles from '../../css/Bar'
import Common from './Common'

export default () =>
  <div className={styles.container}>
    <span>Bar -- loaded!!</span>
    <Common />
  </div>

```
Now when I go to `http://localhost:3000/Bar` directly, I see `404 Page not found` Error.

In server code, we don't send this Common chunk on initial render along with Bar. I don't really know how to fix this. Any idea?

**Comment by faceyspacey** [comment]
We might have come up with a semi solution. Search the issues of all related isssues for "commonsChunkPlugin async"

And something should come up.

The solution ultimately will be to a PR to get this to work extremely correctly. And it likely can't be fully automatic. 

Anyway right now it doesn't import multiple js files. Just one js and one css.
