### ISSUE TITLE
Show loading component after specified delay

### ISSUE THREAD

**Issue by MartinCerny-awin** [faceyspacey/react-universal-component#44]
It would be nice if there is a delay option which has the opposite behaviour to minDelay. Loading component would be shown only after specified time. I know that you have described the reasoning for this at https://medium.com/faceyspacey/code-cracked-for-code-splitting-ssr-in-reactlandia-react-loadable-webpack-flush-chunks-and-1a6b0112a8b8 but most of my components loads in 200-300 ms and I do not want to specify minimal delay and thus increase the time for which loading component should be shown.

I would prefer to have option to avoid flashing screen by not showing anything for a specified time.

**Comment by faceyspacey** [comment]
That doesn't solve any problem. You can still have flashing there is the load time is close to the specified time. The best option is 0ms in that case. 

Who's to say it will load in 10ms (causing flashing) in a real app. It won't. It won't be consistent for anyone. It will be dependent on internet connections.

Also this decision was already made. I don't want to introduce 2 similar options right now. Fork it and add your own if you really need it. But it won't be added any time soon. If some foolproof report (like with lots of examples) was produced to indicate my assessment is wrong, then maybe we'll add another option. 

For now I'm gonna have to close this. Sorry brother.
