### ISSUE TITLE
HMR does not work in some case

### ISSUE THREAD

**Issue by hrasoa** [faceyspacey/react-universal-component#46]
I cloned the [universal-demo](https://github.com/faceyspacey/universal-demo) and tested it locally, everything was working well (ssr, hmr).

Now I wanted to test how it behaves when adding an async component directly on the ```App.js```. 
I created one file under ```src/components/Test.js```:
```jsx
import React from 'react'
export default () =>
  <div>
    <h1>Test</h1>
  </div>
```

And I added in ```src/components/App.js```:
```jsx
const TestComponent = universal(import('./Test'));
...
render() {
  ...
  <TestComponent />
  ...
}
```
After updating ```Test.js```, HMR does not work:
```
[HMR] The following modules couldn't be hot updated: (Full reload needed)
[HMR]  - ./src/components/Test.js
```

**Comment by faceyspacey** [comment]
Try adding it a component imported into App. HMR has always been finicky, with or without universal, and there some places where it doesn't work well. Particularly places closes to where module.hot.accept is.

Try adding a few components, each with their own css. It may have to do with the fact that there is no CSS imported too.

**Comment by faceyspacey** [comment]
Try making it look closer to the working boilerplate until you isolate and find the thing that makes it work and not work.

**Comment by hrasoa** [comment]
Found the issue, I played with the webpack config and seems like we can't separate the main and vendor entry points like this:

```js
entry: {
  main: 'src/index.js'
  vendor: ['react', ...]
}
...
new webpack.optimize.CommonsChunkPlugin({
  name: ['vendor'],
  filename: '[name].js',
  minChunks: Infinity
}) 
```
