### ISSUE TITLE
Chunk disappears on hot module reload

### ISSUE THREAD

**Issue by mhaagens** [faceyspacey/react-universal-component#49]
The universal-component works fine initially, loading the chunk on route change, but whenever I update the lazy-loaded component ("Home.js"), it just disappears. universal-component doesn't report any errors, and Webpack just tells me App and Home has been updated and everything is fine. Am I missing something in my config, or do you have any suggestions as to why it's happening?

.babelrc
```
{
	"presets": [["env", { "modules": false }], "react", "stage-2"],
	"plugins": ["react-hot-loader/babel"]
}
```
index.js
```
import React from "react";
import { render } from "react-dom";
import { BrowserRouter } from "react-router-dom";
import { AppContainer } from "react-hot-loader";

import "./styles/App.scss";
import App from "./components/App";

const renderApp = Component => {
  render(
    <AppContainer>
      <BrowserRouter>
        <Component />
      </BrowserRouter>
    </AppContainer>,
    document.getElementById("root")
  );
};

renderApp(App);

if (module.hot) {
  module.hot.accept(["./components/App"], () => {
    renderApp(App);
  });
}

```
App.js
```
import React, { Component } from "react";
import { Route } from "react-router-dom";
import universal from "react-universal-component";

// Sync components
import TopBar from "./shared/TopBar";

// Async components
const Home = universal(props =>
  import(/* webpackChunkName: 'home' */ "./Home.js"), {
    chunkName: "home"
  }
);

class App extends Component {
  render() {
    return (
      <div id="App">
       <TopBar />
        <main>
          <Route path="/test" component={Home} />
        </main>
      </div>
    );
  }
}

export default App;
```

**Comment by faceyspacey** [comment]
this is incorrect:

```js
if (module.hot) {
  module.hot.accept(["./components/App"], () => {
    renderApp(App);
  });
}
```

it should be:

```js
if (module.hot) {
  module.hot.accept(["./components/App"], () => {
    const App = require("./components/App").default
    renderApp(App);
  });
}
```

you have to require it again.

**Comment by mhaagens** [comment]
You don't have to re-require when you're using Webpack 2+ with ES modules, ref [React Hot Loader 3 Guide](https://github.com/gaearon/react-hot-loader/tree/master/docs#webpack-2).

Hot reloading works fine except for components I import normally, but not with universal-component.

**Comment by faceyspacey** [comment]
yea, i saw that, but i still it do the old way--cuz ultimately HMR is still very finnicky in many places, with or without react-universal-component. 

...a repro would help. RUC has greatly been optimized to work with dynamic expressions for your imports (i.e. ````props => import(`./${props.page}`)```. Perhaps something is now broken for static *dynamic imports*. I doubt it though.

The other thing to do is to open `node_modules/dist/index.js` and logging to `componentWillMount`, `componentWillReceiveProps` and `render`, and see if they are in fact being called when you make an update. In `componentWillReceiveProps` you will see some HMR related things to log to get some insight into whether it's working or not. 
 
Here's the relevant part:
https://github.com/faceyspacey/react-universal-component/blob/master/src/index.js#L156

My guess is life-cycle methods are not being called properly or perhaps you're using Redux or another container component which blocks re-rendering. Either way, the primary problem is likely there is no component in the universal HoC's state. It's weird that nothing renders. I've never seen that before--which leads me to think it's something custom you're doing inside the actual component you're dynamically importing.

Either way, if you log it you'll get a very good idea of what's happening and what isn't.

**Comment by faceyspacey** [comment]
Doin a little cleanup. I'm going to close this. Feel free to re-open or continue the conversation if you discover any more relevant info.

**Comment by olslash** [comment]
this happened to me until i added `babel-plugin-universal-import` to my build. kind of hidden in the middle of the readme, if you ask me 😛
