### ISSUE TITLE
Webpack extensions configuration is ignored

### ISSUE THREAD

**Issue by Kurounin** [faceyspacey/react-universal-component#50]
When using it like this, in a project that contains typescript files (.tsx compiles to .jsx)
```javascript
const UniversalComponent = universal(({ page }) => import(`./pages/${page}`), {
    minDelay: 500,
    loading: Loading,
    error: Err
})
```
Webpack tries to bundle all the files in that directory, including the .tsx files, even though there is no loader defined for it and the extensions is defined as 
```javascript
    resolve: {
        extensions: ['.jsx', '.js', '.sass', '.scss'],
    },
```
To ignore the compile errors, I temporarily added the _ignore-loader_ for .tsx files. Is there a way to configure this behaviour. Should I open this issue on webpack?

**Comment by faceyspacey** [comment]
This is something I too have wanted answers about. I keep recommending using this plugin:
https://webpack.js.org/plugins/context-replacement-plugin/

but I don't know if anyone has used it to ignore files. I dont think this is ultimately an issue. It's just how webpack works. And there are tools like the one you used and the CR plugin. Can you give it a try and let me know if it works?

**Comment by Kurounin** [comment]
Thanks for the suggestion. Using that plugin, webpack generates chunks only for the jsx files, but there's another issue.
Originally it generated these chunks:
```
                    Asset       Size  Chunks                    Chunk Names
                  main.js    2.72 MB       6  [emitted]  [big]  main
            pages/Home.js    39.7 kB       0  [emitted]         pages/Home
        pages/NotFound.js    1.22 kB       2  [emitted]         pages/NotFound
    pages/NotFound-tsx.js  405 bytes       3  [emitted]         pages/NotFound-tsx
      pages/Market-tsx.js  401 bytes       4  [emitted]         pages/Market-tsx
        pages/Home-tsx.js  397 bytes       5  [emitted]         pages/Home-tsx
          pages/Market.js    2.67 kB       1  [emitted]         pages/Market
```
Using this configuration:
```javascript
        new webpack.ContextReplacementPlugin(
            /^\.\/pages$/,
            /\.jsx?/
        ),
```
I get these chunks
```
                    Asset       Size  Chunks                    Chunk Names
                  main.js    2.72 MB       3  [emitted]  [big]  main
        pages/Home-jsx.js    39.7 kB       0  [emitted]         pages/Home-jsx
      pages/Market-jsx.js    2.67 kB       1  [emitted]         pages/Market-jsx
    pages/NotFound-jsx.js    1.22 kB       2  [emitted]         pages/NotFound-jsx
```
which can not be used, because it tries to find to find the chunk named `./NotFound`
Is there a way to control the generated name of the chunks?

**Comment by faceyspacey** [comment]
It's generated by the name of the files. Someone started a PR to let you name it through magic comments but it's not done.

**Comment by Kurounin** [comment]
After having a look at `ContextModule`, it seems webpack tries to load a dependency first without an extension (./Home), then with the extension found in that folder (./Home.jsx, ./Home.tsx).
When using `ContextReplacementPlugin` regExp option to filter the dependencies that are loaded I was left only with `./Home.jsx` which resulted in a chunk named `pages/Home-jsx` which couldn't be used.
To workaround the issue I modified the regex to keep only the dependency without an extension (which actually resolves to the .jsx file according to my webpack config):
```javascript
        new webpack.ContextReplacementPlugin(
            /^\.\/pages$/,
            /[^.]{4}$/
        ),
```
Using the above regex I get the desired outcome
```
                Asset       Size  Chunks                    Chunk Names
        pages/Home.js    39.7 kB       0  [emitted]         pages/Home
      pages/Market.js    2.66 kB       1  [emitted]         pages/Market
    pages/NotFound.js    1.21 kB       2  [emitted]         pages/NotFound
              main.js    2.72 MB       3  [emitted]  [big]  main
```
Thanks for guiding me in the right direction.

**Comment by faceyspacey** [comment]
glad to hear it! ...been recommending this approach for a while, and you're the first to finally prove it works.
