### ISSUE TITLE
@types webpack doesn't contain require.resolveWeak()

### ISSUE THREAD

**Issue by MRJCrunch** [faceyspacey/react-universal-component#51]
I tried to use react-universal-component with typescript and bumped into this problem. Could you add a type definition for resolveWeak to webpack?

**Comment by faceyspacey** [comment]
i'm not a big TS guy. Isn't it a case of just PRing the definition on DefinitelyTyped?

**Comment by MRJCrunch** [comment]
Yes, could you create a PR for it?

**Comment by faceyspacey** [comment]
i could, but i wont have time any time soon. is there something preventing you from doing it?
