### ISSUE TITLE
Wrapping component in HoC breaks import

### ISSUE THREAD

**Issue by pho3nixf1re** [faceyspacey/react-universal-component#57]
When I wrap my 'page' components in an HoC, such as redux `connect`, the error `module not found` is thrown. I presume this has something to do with chunk names and the babel dual import plugin but I'm really not sure. Below is my example Switcher component and the page component that is breaking.

```jsx
import React from 'react';
import { connect } from 'react-redux';
import universal from 'react-universal-component';

import Loading from '../Loading';
import Err from '../Err';

const UniversalComponent = universal(
  ({ page }) => import(`../../pages/${page}`),
  {
    minDelay: 300,
    loading: Loading,
    error: Err,
  }
);

const Switcher = ({ page }) => <UniversalComponent page={page} />;

export default connect(({ page }) => ({
  page,
}))(Switcher);

```

```jsx
import React from 'react';
import { connect } from 'react';
import { selectContent } from '../../store/content/selectors';
import styles from './index.scss';

const MyPage = ({ myPage: { title, content } = {} }) => (
  <div className={styles.container}>
    <div className={styles.innerContainer}>
      <h1>{title}</h1>
      <p>{content}</p>
    </div>
  </div>
);

export default connect(state => ({
  myPage: selectContent(state),
}))(MyPage);

```

If I just `export default MyPage;` everything works as expected. _Any_ HoC wrappers cause the error.

**Comment by pho3nixf1re** [comment]
I am so so very wrong. Consider this report invalid. Closing.

**Comment by serus22** [comment]
please, how did u fixed it man ?

**Comment by pho3nixf1re** [comment]
See line 2 in the `MyPage` component in my example. I'm doing `import { connect } from 'react';` which is incorrect. It should be `import { connect } from 'react-redux';`. It was all just a typo on my part.

**Comment by serus22** [comment]
hm, damn, i am using material ui and there is withStyles hoc wrapper, and when i am using it i have problem with suggestion for import, same when using apollo client for react, there is graphql() wrapper and it breaks import 2, no err. just ide (webstorm) cant see those wrapped components, i read issue wrong sry my bad, i thought its something simliiar, but TY for reply
