### ISSUE TITLE
Exceptions in wrapped render function caught --> "Uncaught TypeError: Cannot read property '_currentElement' of null"

### ISSUE THREAD

**Issue by hedgepigdaniel** [faceyspacey/react-universal-component#63]
Hello, thanks for all your work - I'm having a great time with all your recent react stuff :)

I've been having a hard time debugging errors caused by exceptions thrown in render functions of my components when they are wrapped by react-universal-component. The eventual result is that the component doesn't mount properly and there are lots of cryptic errors of the form `Uncaught TypeError: Cannot read property '_currentElement' of null`. Usually these errors are caused by some exception that is raised by the render function of my component, e.g.
```javascript
class BuggyComponent extends PureComponent {
  render() {
    return <div>{this.props.undefined.raisesException()}</div>;
  }
}
```

I debugged according to the instructions here https://github.com/facebook/react/issues/6895#issuecomment-281405036, but breaking on all exceptions and trying to guess which one is the problem is very slow and tedious, not to mention that working out what this cryptic error message means is already quite a hurdle if you don't already recognise it.

Here is a trace of where the exception is caught:
```

(anonymous) | @ | VM29805:1
-- | -- | --
  | (anonymous) | @ | index.js?2bb8:249
  | Promise rejected (async) |   |  
  | requireAsync | @ | index.js?2bb8:248
  | requireAsync | @ | createPrototypeProxy.js:44
  | componentWillMount | @ | index.js?2bb8:170
  | componentWillMount | @ | createPrototypeProxy.js:44
  | (anonymous) | @ | ReactCompositeComponent.js:348
  | measureLifeCyclePerf | @ | ReactCompositeComponent.js:75
  | performInitialMount | @ | ReactCompositeComponent.js:347
  | mountComponent | @ | ReactCompositeComponent.js:258
  | mountComponent | @ | ReactReconciler.js:46
  | performInitialMount | @ | ReactCompositeComponent.js:371
  | mountComponent | @ | ReactCompositeComponent.js:258
  | mountComponent | @ | ReactReconciler.js:46
  | performInitialMount | @ | ReactCompositeComponent.js:371
  | mountComponent | @ | ReactCompositeComponent.js:258
  | mountComponent | @ | ReactReconciler.js:46
  | performInitialMount | @ | ReactCompositeComponent.js:371
  | performInitialMountWithErrorHandling | @ | ReactCompositeComponent.js:317
  | mountComponent | @ | ReactCompositeComponent.js:256
  | mountComponent | @ | ReactReconciler.js:46
  | performInitialMount | @ | ReactCompositeComponent.js:371
  | mountComponent | @ | ReactCompositeComponent.js:258
  | mountComponent | @ | ReactReconciler.js:46
  | mountComponentIntoNode | @ | ReactMount.js:104
  | perform | @ | Transaction.js:140
  | batchedMountComponentIntoNode | @ | ReactMount.js:126
  | perform | @ | Transaction.js:140
  | batchedUpdates | @ | ReactDefaultBatchingStrategy.js:62
  | batchedUpdates | @ | ReactUpdates.js:97
  | _renderNewRootComponent | @ | ReactMount.js:320
  | _renderSubtreeIntoContainer | @ | ReactMount.js:401
  | render | @ | ReactMount.js:422
  | render | @ | topBarLoader.jsx:12
  | ./client/loaders/OLTopBar/topBarLoader.jsx | @ | topBarLoader.jsx:24
  | __webpack_require__ | @ | bootstrap 055924e…:691
  | fn | @ | bootstrap 055924e…:114
  | 4 | @ | topBarLoader.jsx:11
  | __webpack_require__ | @ | bootstrap 055924e…:691
  | webpackJsonpCallback | @ | bootstrap 055924e…:25
  | (anonymous) | @ | OLTopBarLoader.js:1


```
` index.js?2bb8` is react-universal-component.

I noticed that after the exception is thrown, [this code](https://github.com/faceyspacey/react-universal-component/blob/master/src/index.js#L226) is reached. At this point, `error` is the exception that my component threw, but `this.props` is the props of the wrapped component (so `this.props.onError` is undefined, even if I pass a function as an option to `universal` when I wrap the component). Hence the condition fails and the exception is silently caught. I'm not sure if this is intended or not?

I wonder if there is a simple way to at least print the error to the console so that its reasonably clear what first went wrong to cause these cryptic react errors?

**Comment by faceyspacey** [comment]
hmmm. ...I plan to get way better at reporting errors via a `debug` mode in the next major version of all these tools. 

`this.props.onError` should be the props passed to the wrapped component.  I'm not sure how it could be disregarded.
