### ISSUE TITLE
Preload does not load CSS

### ISSUE THREAD

**Issue by nikglavin** [faceyspacey/react-universal-component#67]
Is it possible to fetch the corresponding split css when preloading a component?

**Comment by faceyspacey** [comment]
Unless I'm mistaken, it should do just that if you have `babel-plugin-universal-import` setup. It should be no different than normal.

**Comment by nikglavin** [comment]
Thanks for the reply looked into it and it indeed works as you say. 

The caveat is that the path used to require the component must match the chunkName in webpack ie no relative path need to resolve the preload from the src directory. 

Side note you have done some really nice work with all this universal stuff ! A++ 👌

**Comment by daisy-github** [comment]
On first time opening the site after build, css get distorted after that its showing loader from universal import...any idea to resolve this issue

**Comment by ScriptedAlchemy** [comment]
Can I see an example of the code or a demo repo. How are you using Universal?

**Comment by ScriptedAlchemy** [comment]
Css is loaded via extract css chunks. And is not managed under universal. Is this in initial page load with SSR?

**Comment by daisy-github** [comment]
Thank you for reply. Yes this is in initail page load with SSR

I am extracting css using mini-css-extract-plugin
`    new MiniCssExtractPlugin({
      // Options similar to the same options in webpackOptions.output
      // both options are optional
      filename: '[name].[hash].css',
      chunkFilename: '[id].[hash].css',
    }),`
using webpack-flush-chunks  to get css and js chunks like below
`const { js, styles, cssHash, scripts, stylesheets } = flushChunks(
    clientStats,
    { chunkNames, before: ['vendor', 'client'] },
  );`

then adding it in head tag

`<head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      ${title}
      ${meta}
      ${script}
      ${styles}
      <link rel="shortcut icon" href="/public/favicon.ico"/>
      <link rel="stylesheet" href="/public/css/slick.css"></link>
      <link href="https://fonts.googleapis.com/css?family=Lato:400,400i,700,700i,900,900i" rel="stylesheet" async="true">
      <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i" rel="stylesheet" async="true">
    </head>`
