### ISSUE TITLE
Question: Universal component loading markdown?

### ISSUE THREAD

**Issue by primozs** [faceyspacey/react-universal-component#69]
Would it be possible to directly load markdown file...?

https://blog.mapbox.com/introducing-jsxtreme-markdown-a64c6b404596
https://github.com/mapbox/jsxtreme-markdown

I was playing with redux-first-router-demo and it works if i wrap the markdown file like this:
```
import AddonsMD from './Addons.md';
import React from 'react';

const Addons = (props) => {
  return (
    <AddonsMD />
  );
};

export default Addons;
```
If I remove Addons.js file then UniversalComponent in Switcher does not find Addons.md insead. 

```
in client and server webpack config I added this:

{
        test: /\.md/,
        use: [
          require.resolve('babel-loader'),
          require.resolve('@mapbox/jsxtreme-markdown-loader'),
        ]
},
```
cheers!

**Comment by faceyspacey** [comment]
That's a tough one. I just don't know. I'd setup a bare bones app to isolate the capability you're trying to test for. I.e. without RUC, and see if webpack is even capable of code-splitting .md files. 

That said, even if that works, my best guess is there might be some problems in my setup where it only supports css and js files. Wrapping it is likely your best bet.

**Comment by primozs** [comment]
Yes, thx! Have a nice day!
