### ISSUE TITLE
Error component not working properly with dynamic import - when not initial load

### ISSUE THREAD

**Issue by timkindberg** [faceyspacey/react-universal-component#71]
### Scenario 1:

**Steps:**
1. Use code below
2. Click Baz button

**Expected**: Should show the default `"Error: Cannot find module './Baz'."` message
**Actual**: Nothing happens

```jsx
import React from 'react'
import universal from 'react-universal-component'

const LazyTab = universal(({ tab }) => import(`./${tab}`))

export default class App extends React.Component {
  state = { selected: 'Home' }

  render() {
    return (
      <div>
        <LazyTab tab={ this.state.selected } />
        <button onClick={ () => this.setState({ selected: 'Baz' }) }>Baz</button>
      </div>
    )
  }
}
```

### Scenario 2:

Works as expected, I see the error message. Baz is the initial state, no button clicking.

```jsx
import React from 'react'
import universal from 'react-universal-component'

const LazyTab = universal(({ tab }) => import(`./${tab}`))

export default class App extends React.Component {
  state = { selected: 'Baz' }

  render() {
    return (
      <div>
        <LazyTab tab={ this.state.selected } />
      </div>
    )
  }
}
```

**Comment by faceyspacey** [comment]
hmm. that's not good. Is the loading... indicator showing during that time? I don't suppose you have a precise repro?

**Comment by timkindberg** [comment]
Nothing shows. 

The code above is the entirety. You just need a valid Home component file  to load. And make sure there is no Baz file present.

**Comment by faceyspacey** [comment]
Just FYI, I probably won't be able to get to this for a while. any investigation or PRs welcome. Clearly the error is being suppressed and not bubbling up to the HoC which would then know to show the `Error` component.

**Comment by timkindberg** [comment]
I understand. Unlikely I’ll fix it but you never know!!

**Comment by lawwantsin** [comment]
I'm getting a similar error to this.  
`chunk not available for synchronous require yet: /Article: Cannot find module '/Article' Error: Cannot find module '/Article'`
![image](https://user-images.githubusercontent.com/18623/35475874-de2bdb00-035a-11e8-93ae-14443633469b.png)

I'm following the https://github.com/faceyspacey/universal-demo almost exactly, except i'm using the ReactRouter StaticRouter.
My repo is at https://github.com/lawwantsin/webpack-course/tree/css-chunks-final

any help is appreciated.  thanks.

**Comment by faceyspacey** [comment]
@lawwantsin not sure if it's related to the original issue here, but I left you more details just now in gitter to debut your StaticRouter setup.

**Comment by mtphil** [comment]
@timkindberg @faceyspacey - did anyone ever figure this out? I'm having this exact issue as well, discovered it while following this tutorial - https://egghead.io/lessons/react-preload-a-universal-component-on-demand-with-the-preload-method - strangely it doesn't occur in the video, but does when I copy the video's code directly from the repo and run it myself.

**Comment by mtphil** [comment]
For now, this is the hack I'm having to use to achieve similar functionality: 

`const UniversalComponent = universal(props => import(`./components/${props.page}`), {
});

class App extends React.Component {
    constructor() {
        super();
        this.state = {
        };
    }

    setError() {
        this.setState({selected: "ComponentLoadErrorHandler"})
    }

    render() {
        return (
            <div>
                <UniversalComponent
                    page={ this.state.selected }
                    onError={() => this.setError()}
                />
                <button onClick={ () =>
                    this.setState({ selected: 'HomeTab' }) }>
                    Home
                </button>
                <button onClick={ () =>
                    this.setState({ selected: 'Error' }) }>
                    Error
                </button>
            </div>
        )
    }
}

export default App;`

**Comment by timkindberg** [comment]
@mtphil I never dug into it. I ran into the bug while making my video :), I had to do a bit of editing and presentation kung-fu to hide the bug :)

**Comment by faceyspacey** [comment]
this has now been fixed. do an upgrade of the package and you will have it.
