### ISSUE TITLE
"Some" components don't load synchronously on the server side

### ISSUE THREAD

**Issue by edude03** [faceyspacey/react-universal-component#73]
Hello,

I'm running into an issue that's hard to describe, so I hope this makes sense. 

I'm using the universal component with Typescript and not using babel. I'm manually creating an import as described in the `babel-plugin-universal-import` readme, and it works for 1 of 3 of my example components. 

The strange thing is all three components are essentially the same, however when I step through the code, it seems like [https://github.com/faceyspacey/react-universal-component/blob/3404664eb8d48e9973f725bd257b19f89ad02603/src/requireUniversalModule.js#L61-L81](this) chunk of code is getting the wrong module type.

Let me explain.

On line 61, `var weakId = (0, _utils.callForString)(resolve, props);` returns `40`, so it is getting a module ID.

On line 63, `__webpack_require__.m[weakId]` returns what looks like a module function to me it looks something like this

```
(function(module, __webpack_exports__, __webpack_require__) {

"use strict";
eval("Object.defineProperty(__webpack_exports__, \"__esModule\", { value: true });\n/* harmony import */ var __WEBPACK_IMPORTED_MODULE_0_react__ = __webpack_require__(0);\n/* harmony import */ var __WEBPACK_IMPORTED_MODULE_0_react___default = __webpack_require__.n(__WEBPACK_IMPORTED_MODULE_0_react__);\n/* harmony import */ var __WEBPACK_IMPORTED_MODULE_1_react_foundation__ = __webpack_require__(1);\n/* harmony import */ var __WEBPACK_IMPORTED_MODULE_1_react_foundation___default = __webpack_require__.n(__WEBPACK_IMPORTED_MODULE_1_react_foundation__);\n/* harmony import */ var __WEBPACK_IMPORTED_MODULE_2__styles_sass__ = __webpack_require__(123);\n/* harmony import */ var __WEBPACK_IMPORTED_MODULE_2__styles_sass___default = __webpack_require__.n(__WEBPACK_IMPORTED_MODULE_2__styles_sass__);\n/* harmony import */ 
```
(etc)

Which looks like a transpiled version of my module, so that's good.

Where things get weird is in `tryRequire` function, it seems it retries to load the module. Eyeballing the code [https://github.com/faceyspacey/react-universal-component/blob/master/src/utils.js#L21-L42](here) it seems that even though it has a copy of the module, it does a webpack require again with the module ID.

The really weird part is it returns a plain object, with nothing but `{esModule: true}` and none of the other props.

I imagine this has something to do with the webpack require not loading the module by calling the function that was previously returned, but that's just a guess.

Any idea what's causing this and how I could fix it?

**Comment by faceyspacey** [comment]
Honestly, I can't say for sure. If you're copying what the babel-plugin does exactly, then it's likely not an issue related to typescript, but an issue related to general configuration pitfalls.

- Are you handling externals properly: https://github.com/faceyspacey/webpack-flush-chunks#externals (a lot of people have had this issue)
- Are you replicating the nested call to `universalImport`?
- Are you using dynamic expressions in your dynamic import, i.e. using the props argument to dynamically determine what component to import?
- there's a typescript repo being worked on here: https://github.com/faceyspacey/universal-demo/issues/22 (perhaps its author may have some insights to share)

**Comment by faceyspacey** [comment]
Also I just made an update that should make it easier for typescript users. Upgrade your package, and you leave out the nested `universalImport` call.

So before you might have had this:

```js
import universal from 'react-universal-component'
import universalImport from 'babel-plugin-universal-import/universalImport.js'
import importCss from 'babel-plugin-universal-import/importCss.js'

const UniversalComponent = universal(props => universalImport({
  chunkName: props => props.page,
  resolve: props => require.resolveWeak(`./${props.page}`),
  load: props => Promise.all([
    import( /* webpackChunkName: '[request]' */ `./${props.page}`),
    importCss(page)
  ]).then(proms => proms[0])
}));
```

Now you can have this:

```js
import universal from 'react-universal-component'
import importCss from 'babel-plugin-universal-import/importCss.js'

const load = props => Promise.all([
    import( /* webpackChunkName: '[request]' */ `./${props.page}`),
    importCss(page)
  ]).then(proms => proms[0])

const UniversalComponent = universal(load, {
  chunkName: props => props.page,
  resolve: props => require.resolveWeak(`./${props.page}`)
});
```

**Comment by faceyspacey** [comment]
https://github.com/faceyspacey/babel-plugin-universal-import#typescript-and-non-babel-environments
