### ISSUE TITLE
issues in type definitions

### ISSUE THREAD

**Issue by hurrtz** [faceyspacey/react-universal-component#80]
Hey,

I have two issues from react-universal-component/index.d.ts:

`ERROR in [at-loader] ./node_modules/react-universal-component/index.d.ts:89:36 
    TS2304: Cannot find name 'C'.`

This might be a typo - I guess "C" should have been "P".

`ERROR in [at-loader] ./node_modules/react-universal-component/index.d.ts:148:15 
    TS2304: Cannot find name 'Export'.`

Here a type for "Export" is missing. It gets gets typed later on but in this scope it is not defined.

I have checked and both errors seem to be legit. Can you please look this up? For the record - we have just recently startet moving our React app from standard jsx to typescript tsx. Before that the errors didn't occur.

**Comment by faceyspacey** [comment]
Here's the recent PR that added them:

https://github.com/faceyspacey/react-universal-component/pull/75

@forabi any idea what's going on?
