### ISSUE TITLE
Fetching data

### ISSUE THREAD

**Issue by suciuvlad** [faceyspacey/react-universal-component#81]
I have a loadGetInitialProps function that is being executed server-side when the app loads and on the client side when the route changes:

```
export const loadGetInitialProps = (props: Props) => {
  const {
    req, res, routes, store, pathname
  } = props;

  const path = req && req.path || pathname;

  const branch = matchRoutes(routes, path);

  return branch.map(({ route }) =>
    route.component.preload && route.component.preload().then((comp) => {
      const initialProps = comp.getInitialProps;
      return initialProps instanceof Function
        ? initialProps({ req, res, store })
        : Promise.resolve(null);
    }));
};
```
Inside the component, it is defined as a static method:

```

class MyComponent extends Component {
  static getInitialProps () {
    //dispatch action to fetch the require data
  }
  render () {
    return(
      <div></div>
    );
  }
}
```

This works as expected since the store is updated when the action is dispatched but now it'd like to adjust it to work more like the method in the next.js framework. Basically, to have getInitialProps return an object instead, that is eventually available as props on the component.

My first thought was to do something along these lines(theoretical code):

```
route.component.preload && route.component.preload().then((comp) => {
      const initialProps = comp.getInitialProps;

      const props = initialProps instanceof Function
        ? initialProps({ req, res, store })
        : Promise.resolve(null);

      // override the component before rendering and include the props
      route.component = React.cloneElement(comp, props);

       return props;
    }));
```

My issue is that i don't have access to the real component in order to be able to clone it.

@faceyspacey What do you think ? :)

**Comment by faceyspacey** [comment]
Since static methods are hoisted, you could make a static method that returns the inner component:

```js
class MyComponent extends React.Component {
   static getComponent() {
       return MyComponent
   }
}
```

and then use `React.createElement` instead of `cloneElement`.
