### ISSUE TITLE
User supplied `isLoading` takes precedence over `loadingTransition`

### ISSUE THREAD

**Issue by kshahani** [faceyspacey/react-universal-component#91]
`loadingTransition=false` only seems to keep the previous route component while asynchronously requiring modules, but if dev wants to force a loading state via `isLoading`, the default `Loader` component will still be rendered despite supplying `loadingTransition = false`. See https://github.com/faceyspacey/react-universal-component/blob/v2.8.0/src/index.js#L244.

In our case, we're fetching data for the next page prior to loading the next route component, so we'd want to supply the `isLoading` prop to the universal component AND keep the previous route in view until the data is fetched.

I think this could be resolved by changing this line to `if (isLoading && !loadingTransition)`, but maybe this is not the desired use case...

**Comment by faceyspacey** [comment]
You mean `isLoading && loadingTransition` right? That would be an acceptable PR.

`loadingTransition` by default is `true`, so this change won't affect the most common use-case here, but simply better optimize your use case. That said, it is a decision, as some people may want to show the `loading...` screen in that case.

You can solve this by simply passing the `isLoading` prop as `false` after initial mount (even if in fact loading), thereby solving what I'm guessing is your desired experience of being able to control the display of your `loading...` component based on data, but only on initial load.
