### ISSUE TITLE
Magic comments for chunk names

### ISSUE THREAD

**Issue by amangeot** [faceyspacey/react-universal-component#93]
Hello,
Thank you for this awesome project. I'm trying to set names for my chunks as is:
```
const Component = universal(() => import(/* webpackChunkName: "super-chunk" */ './components/Component'), { // eslint-disable-line max-len
  chunkName: 'super-chunk',
})
```

But only `components/Component` will appear in `chunkNames`.

Did I miss something?

**Comment by faceyspacey** [comment]
Those chunk names are not honored. It only works by automatically creating them for you based on the module's file path. There is a PR that wasn't quite finished to address this:

https://github.com/faceyspacey/babel-plugin-universal-import/pull/13

If you wanna help complete that, we can merge it.
