### ISSUE TITLE
Type-definitions

### ISSUE THREAD

**Issue by aneogiarcadix** [faceyspacey/react-universal-component#94]
Using this with typescript is a nightmare. I tried adding this package to webpack externals, and got 'react not found' . Could we have some type definitions fro this and the related packages, so that it works with typescript too.

**Comment by sujitwarrier11** [comment]
got the same problem, with typescript. get the error while trying to import universal
import  universal from 'react-universal-component'

**Comment by aneogiarcadix** [comment]
I was able to make it work by adding a reference to the d.ts file. Turns out the type definitions were already there. My bad 😆 . Also remove the module from webpack externals 😄
