### ISSUE TITLE
<Cmp error={...} /> is a namespace clash

### ISSUE THREAD

**Issue by wmertens** [faceyspacey/react-universal-component#95]
I am using `universal` with great happiness, but I discovered an issue with the resulting component: it eats `isLoading` and `error` props, both pretty likely to be real component props.

Case in point, I'm wrapping react-select as a Field for redux-form, and having a from error results in the error being rendered instead of the component. It is very inconvenient to have to rename the error using 2 wrapper components :(

I propose to namespace these props, e.g. `universalLoading` and `universalError`. This could be made optional?

**Comment by osorokotyaga** [comment]
Same problem. Renaming these props will be very helpful.

**Comment by Arturszott** [comment]
I have the same situation. I try to integrate universal into our stack: I could rename the prop name of the child component which is loaded but I can't guarantee than someone will not start using `error` or `isLoading`  props.

**Comment by wmertens** [comment]
Options:

1. put all props related to r-u-c under a prop: `universal={{error, isLoading, etc}}`
2. rename props individually: `universalError`, `universalIsLoading`
3. make props configurable: `const Cmp = universal(()=>import('./Cmp'), {errorProp: 'universalError'})`
4. same as 3, but make each prop also configurable as `false` if it should not be used, and default to `false`.

I think I prefer option 4. @faceyspacey if you think this is a good addition I'll be happy to make a PR…

**Comment by faceyspacey** [comment]
Can’t default to false. We need backwards compatibility. 3 + 4 minus defaulting to false.

PR idea approved

**Comment by leebenson** [comment]
@wmertens any news on the proposed PR?

**Comment by wmertens** [comment]
I haven't yet had time for this, but the workaround is this:

```js
export const makeSplitPoint = (fn, options) => {
	const W = universal(
		async () => {
			const real = await fn()
			const C = real.default || real
			return ({_error, _isLoading, ...props}) => (
				<C {...{...props, isLoading: _isLoading, error: _error}} />
			)
		},
		{loading: DefaultLoading, ...options}
	)
	return ({error, isLoading, ...props}) => (
		<W {...{...props, _isLoading: isLoading, _error: error}} />
	)
}
```

Use `makeSplitPoint` as you would `universal`

**Comment by ScriptedAlchemy** [comment]
PR would help. RUC is a pretty small code base
