### ISSUE TITLE
Singleton configuration

### ISSUE THREAD

**Issue by wmertens** [faceyspacey/react-universal-component#96]
It would be nice to be able to set the default configuration so that `universal` uses the same custom  Loader everywhere, for example.

I would normally wrap `universal`, but the Babel plugin requires it to be imported in the file it's being used from, right?

**Comment by faceyspacey** [comment]
Actually you should be able to perform the dynamic import in a different file than where the Hoc is called, but this may change in the future as to support this behavior adds a ton of complexity.

Try wrapping it in your hoc that sets the loader and let me know how it goes.
