### ISSUE TITLE
Exclude staticContext prop before rendering universal component

### ISSUE THREAD

**Issue by corydeppen** [faceyspacey/react-universal-component#97]
In an experiment to use react-universal-component to render dynamic components inside a react-static app, I've run into a slight problem.

> Warning: React does not recognize the `staticContext` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `staticcontext` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

In browsing the react-router issues and from logging the props before the universal component is rendered, it seems the issue is related to the `staticContext` prop that's being spread onto the universal component. I can get around the problem by using the following, but I'd rather not have to do this everywhere I add a universal component.

```ts
const Admin = universal<RouteComponentProps<any>>(import('./pages/Admin'), {
  loading: <div>Loading...</div>,
});

export default () => (
  // ...
  <Route
    path="/admin"
    render={({ staticContext, ...props }) => <Admin {...props} />}
  />
  // ...
);
```

I was wondering how you felt about modifying the `render` method to limit the props by destructuring a series of blacklisted props like `staticContext` that shouldn't be passed along to the universal component.

**Comment by faceyspacey** [comment]
hmm. it doesn't sound like we could ever get every potential blacklisted prop. that doesn't make it sound appetizing unfortunately.

**Comment by corydeppen** [comment]
While I agree it'd be impossible to blacklist every possible prop up front, I thought it might be a way to allow for entries to be added over time and prevent boilerplate from being added to projects.
